-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jan 10, 2024 at 02:42 PM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `db_sentimen_food`
--

-- --------------------------------------------------------

--
-- Table structure for table `dataset`
--

CREATE TABLE `dataset` (
  `id` int(11) NOT NULL,
  `owner` varchar(50) NOT NULL,
  `caption` text NOT NULL,
  `timestamp` varchar(100) NOT NULL,
  `label` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `dataset`
--

INSERT INTO `dataset` (`id`, `owner`, `caption`, `timestamp`, `label`) VALUES
(801, 'dyodoran', 'Rasanya ketika pas nge-Adzanin kamu adalah hal yang sangat luar biasa bapak rasakan  Tumbuh besar menjadi soleh, berbakti kepada bapak mami & bermanfaat untuk masyarakat anakku sayang \n\nTerimakasih ya Allah SWT & Terimakasih buat temen2 semua yang kemarin udah mendoakan Alhamdulillah semuanya lancar\n\n@benitaadzani kamu hebat ❤️\n\n#bendyoFamily', '2023-05-28T03:07:25.000Z', 'Positif'),
(802, 'dyodoran', 'KOMEN POSTINGAN INI LANGSUNG DAPET VOUCHER MAKAN GRATIS!\n\nUhuyy, ada yang baru lagi nihh di Jogjaa\nNamanya Titik Kumpul alias Tikum, yang buka dari jam 06.30 - 22.00!\nBubur Ayam Spesial Tikumnya BEUH.. recommended!\nBuat makan siang kalian bisa pilih Nasi Rempah Tikum atau lainnya yaa\n\n‌Nah spesial di tanggal tua, Tikum mau bagiin VOUCHER MAKAN GRATIS buat Grand Opening Tikum tanggal 28 Oktober!\n\nKalian tinggal komen #LangsungKeTikum di reels ini dan follow @tikum.indonesia , pemenangnya akan langsung di dm oleh Tikum!\n\nIngat, cek DM kalian terus Break Dulu, Kita Ketemu di Grand Opening Tikum ya lurr\nSugeng dhahar!\n‌\n#LangsungKeTikum #Tikum #TiktikKumpul #KulinerJogja #JogjaFoodHunter', '2023-10-26T04:32:04.000Z', 'Positif'),
(803, 'dyodoran', 'Begitu ya kata-kata hari ini', '2023-10-29T05:37:01.000Z', 'Positif'),
(804, 'dyodoran', 'Ini tuh satu satunya warung bakmi jowo yang jual \"Ngarso Dalem\" dan punya 29 MENU!!\nPenasaran tooo sama wujud dan asal usul menu \"Ngarso Dalem\"?\nNdang tonton di Youtube Channel Dyodoran lurrr\n\n#kulinerjogja #kulinerlegendaris #jogjafoodhunter #kulinerindonesia #dyodoranjogja', '2023-10-27T09:29:40.000Z', 'Positif'),
(805, 'dyodoran', 'Ini namanya adalah rute ngidam \n\n#BenDyo #pregnancy #meteng', '2023-01-29T01:43:39.000Z', 'Positif'),
(806, 'dyodoran', 'Udah ngantri 13 porsi, jebul kehabisan lurrr\nBtw ini bukanya jam 11an tapii jam 2 sudah ludes!!\nWarga Jogja ada yang pernah coba?\n\n#kulinerjogja #streetfood #esbuah #jogjafoodhunter #dyodoranjogja', '2023-10-28T09:28:07.000Z', 'Positif'),
(807, 'dyodoran', 'LUAR NEGERI❌❌❌\nGUNUNG KIDUL✅✅✅\n\nSpot nyunset baru di ujung Gunung Kidul lurr!\n\nTersedia bermacam area, mulai dari pool side bar, playground anak, ampli theater, dan center of santorini!\n\nFasilitasnya lengkap, tempatnya nyaman dan instagramable, serta yang terpenting kids friendly! Harga makanannya mulai dari 20 ribuan, HTM sudah termasuk spot foto gratis, cocok pol buat healing bareng keluarga!\n\nNamanya Jungwok Blue Ocean, info tiket masuk dan lainnya ndang follow @jungwokblueocean \n\n#JungwokBlueOcean #JungwokBeach #SantoriniBanget #GunungKidul #WonderfullJogja', '2023-10-24T06:10:27.000Z', 'Positif'),
(808, 'dyodoran', 'Kegiatan dirumah kalau habis nginep di luar kota, nyanyi bareng mas Kenzie sang penakluk dunia. Ada yang mau request lagu apa? Hihihii\n\n#bendyofamily', '2023-10-23T02:57:43.000Z', 'Positif'),
(809, 'dyodoran', 'Ini spot family resto dengan porsi menu yang super bikin kenyang lurr\nTempatnya juga homey pol dan parkirannya luas! Cocok bianget ikii buat kumpul keluarga!!\nWarga CCTV Semlidut ada yang sudah ke sini?\n\n#familytime #familyrestaurant #kulinerbintaro #dyodoran', '2023-10-22T09:34:39.000Z', 'Positif'),
(810, 'dyodoran', 'Kayaknya ini gudeg termurah yang pernah aku temuin di Jogja deh\nSeporsi tuh cuma 5000 dan sudah dapet telur!\nDefinisi penyelamat akhir bulan wgwgwg\n\n#kulinerjogja #kulinermurah #jogjafoodhunter #gudeg #dyodoranjogja', '2023-10-29T09:26:28.000Z', 'Positif'),
(811, 'dyodoran', 'Sekian tahun tinggal di Jogja, akhirnya aku menemukan pelopor warung brongkos lurrr\nJebul yo cedak karo omah wgwgwg\nWarga Jogja ada yang pernah ke sini gakk?\n\n#kulinerjogja #kulinerlegendaris #jogjafoodhunter #jogjaistimewa #brongkos', '2023-10-17T09:30:00.000Z', 'Positif'),
(812, 'dyodoran', 'Murah enak mengenyangkanan \nIni tempatnya di Selatan Dagadu Gedong Kuning nanti ada di sebelah kiri jalan, atau mapsnya : Pecel Lele Lebay Kotagede\n\n#kulinerjogja #pecelleleJogja #jogjamain #jogja #pecellele #pecellelekotagede', '2023-10-21T04:44:07.000Z', 'Positif'),
(813, 'dyodoran', 'Lokasinya ada di perempatan lampu merah, terdengar kurang strategis ya lur?\nTapi jangan salah.. semua menu di sini ludes dalam waktu 3 jam aja!!\nWarga Jogja udah pada nyoba?\n\n#kulinerpedas #kulinerjogja #kulinerjogjamurah #jogjafoodhunter #dyodoranjogja', '2023-10-20T09:31:26.000Z', 'Positif'),
(814, 'dyodoran', 'Salah satu kedai ramen yang jadi juara di lidahku dann kayanya Mas @hobbymakan.id juga!! \nKalian udah pada coba belum nih??\n\n#ramen #ramenhalal #kulinerjogja #jogjafoodhunter #dyodoranjogja', '2023-10-25T09:26:13.000Z', 'Positif'),
(815, 'dyodoran', 'Sampe kangen nih beberapa bulan gak ngumpul karena kemarin baru persiapan lahiran Mas Kenzie. \nSehat sehat yaaa semuanyaaa ❤\n\n#dyodoran', '2023-10-15T09:27:04.000Z', 'Positif'),
(816, 'dyodoran', 'PERTAMA KALI REQUEST MENU MALAH KAGET SENDIRI! \n\nGimana ga kaget, lha porsinya jadi portugal gitu lurr, definisi kenyang maksimal dengan budget hemat!\nIni by request lho ya, kalo kalian sanggup habisin ya monggo pesen juga wgwgwg\n@buburhayam Kotabaru juga menerima pesanan PO Partai Besar yang cocok untuk acara Arisan, Kumpul Keluarga/Kantor, Reuni, dan lainnya!\nPemesanan bisa melalui DM Instagram atau WhatsApp di 0896-7477-6888\nBuka setiap hari dari jam 6 pagi sampai 10 malam, kuliner wajib buat perut keroncongan di Jogja!\n\n#kulinerjogja #kulinerjogjamurah #jogjafood #jogjafoodhunter #buburhayam', '2023-10-19T09:26:41.000Z', 'Positif'),
(817, 'dyodoran', 'Kata pepatah mahal & murah tergantung dompetnya. Iya juga sih\n\n#vespaindonesia #vespa #vespadarling #vespadarling90', '2023-10-19T04:43:49.000Z', 'Positif'),
(818, 'dyodoran', 'SAT SET BELI OLEH OLEH HARGA MIRING DI BANDARA YIA!\n\nAku yakin pasti bukan cuma aku doang yang suka berangkat mepet sampe lupa beli oleh-oleh, ya to?\n\nNah kenalin, ada satu area di Bandara YIA yang jual produk-produk UMKM khas Jogja dengan harga terjangkau, namanya Galeri PKG alias Galeri Pasar Kotagede.\n\nProduknya lengkap, mulai dari fashion, craft, pernak pernik, bahkan ada area belajar membatiknya serta area food court.\n\nYang bikin makin happy nih: ada GRATIS ONGKIR untuk pembelian diatas 50.000 dan BISA DIKIRIM ke SELURUH INDONESIA dan LUAR NEGERI!\n\nInfo promo dan pengiriman selengkapnya bisa langsung cek @pasarkotagedeyia dan @diskopukm.diy yaa \n\nSelamat berbelanja!\n\n#oleholeh #oleholehjogja #diskopukm #jogjaistimewa', '2023-10-16T09:27:13.000Z', 'Positif'),
(819, 'dyodoran', 'TANGGAL TUA JANGAN SEDIH, ADA PROMO TIAP HARI SELAMA BULAN OKTOBER!\n\nBuat kalian pecinta all you can eat harap tenang, Mas Dyo bawa kabar yang bikin senang!\nAda promo diskon 5% yang bisa kalian pake sampai 31 Oktober 2023, maksimal 10 bills di @kakkoii_jogja \nOiya info nihh, meskipun ambil paket reguler, kalian bisa request daging premiumnya lho!\nBebas pilih Saikoro, Rib Eye, Meltique, dan lainnya dengan harga 40 ribuan per 100 gram.\nDurasinya juga bisa pilih yang 90 menit atau 120 menit\n\nSaranku sih pilih 120 menit aja lur, biar puas menikmati 140++ menu dengan diskon!\nInget, reservasi dulu via Whatsapp atau DM Instagram di @kakkoii_jogja yaa\n\n#ayce #kakkoii #kulinerjogja #diskonjogja #jogjafoodhunter', '2023-10-18T09:30:07.000Z', 'Positif'),
(820, 'dyodoran', 'Rapat pemenangan @adhityaputratama   @kemislegii \n\n#kulinergunungkidul #kulinerwonosari #jogja #gunungkidul', '2023-10-15T05:34:14.000Z', 'Positif'),
(821, 'dyodoran', 'Sejauh ini, kayaknya ini bengkel mobil paling pw deh yang pernah tak temuin wwgwg\nWarga Jogja dan sekitarnya ada yang udah ke sini?\n\n#bengkelmobil #bengkelmotor #kulinerkulonprogo #kulinerjogja #dyodoran', '2023-10-13T09:29:42.000Z', 'Positif'),
(822, 'dyodoran', 'PENINGGALAN KULINER LEGENDARIS ERA PENJAJAHAN!!\n\nDari artikel yang aku baca, kuliner ini jadi media penyamaran oleh para penjual untuk mengabarkan situasi terbaru kepada warga di daerah Tuyuhan saat terjadinya Perang Lasem tahun 1734.\n\nSetelah perang selesai, Lontong Tuyuhan jadi kuliner turun temurun yang dilestarikan!\n\nOverall rasanya mirip opor, sedikit lebih pedas dengan porsi yang WUAH... buanyak lurrr\n\nWarga CCTV Semlidut Rembang ada yang pernah coba?\n\n#throwback #throwbackthursday #kulinerlegendaris #kulinerindonesia #dyodoran', '2023-10-12T09:29:32.000Z', 'Positif'),
(823, 'dyodoran', 'Spot sarapan gudeg yang ludes dalam 3 jam!!\nLokasinya emang di pinggir jalan, tapi masakannya BEUH... \nWarga CCTV Semlidut Jogja udah pada nyoba belum nihh??\n\n#gudeg #gudegjogja #sarapanjogja #kulinerjogja #jogjaistimewa', '2023-10-14T09:29:43.000Z', 'Positif'),
(824, 'dyodoran', 'Taman ini sudah berumur 100 tahun dan dibangun ulang di tahun 2023 lalu dibuka untuk publik!\nSatu yang wajib kalian catet: JANGAN PAKE CELANA PENDEK karena ini mash terhitung area Istana Mangkunegaran Solo hehee\nMari menghargai tradisi & budaya negeri sendiri\n\n#kulinersolo #pracimatuin #dyodoran', '2023-10-07T05:28:34.000Z', 'Positif'),
(825, 'dyodoran', 'Spot perkambingan di Utara Jogja yang dagingnya BEUH... guedi guediii\nSaranku kalo mau dateng agak sore, kalian chat/ booking dulu ke warung biar ndak mrongos kehabisan kayak aku\n\n#satekambing #kulinerjogja #kulinerlegendaris #jogjafood #jogjafoodhunter #dyodoranjogja', '2023-10-11T09:30:14.000Z', 'Positif'),
(826, 'dyodoran', 'Warung sop buntut dengan pemandangan 3 gunung sekaligus di Magelang!!\nNyaman pol lurrr\n\n#sopbuntut #kulinermagelang #magelang #magelangexplore #dyodoran', '2023-10-10T09:31:20.000Z', 'Positif'),
(827, 'dyodoran', 'Yang lagi rame di jagad kuliner Jogja: nasi goreng\n5000 dan mie goreng 5000 dengan porsi ugal ugalan lurrr\nWarga Jogja ada yang udah coba?\n\nKalo belum bisa tonton dulu ulasan selengkapnya di youtube channel dodoran yaa\n\n#kulinermurah #kulinerjogja #jogjafood #jogjafoodhunter #dyodoranjogja', '2023-10-06T09:28:04.000Z', 'Positif'),
(828, 'dyodoran', 'Visualisasi ajaa duluuuuuu ❤️ ehehe \n\n#vwclassic #vw', '2023-10-10T02:40:16.000Z', 'Positif'),
(829, 'dyodoran', 'Pagi hari Jumat Kliwon di Sebuah Pasar Hewan Gunung Kidul bersama para blantik \n\n#pasarhewan #gunungkidul', '2023-10-06T02:37:37.000Z', 'Positif'),
(830, 'dyodoran', 'Salah satu kuliner malam Jalan Magelang yang ruaame pol dan buka sampai jam 4 pagi!!\nTotal ada 25 menu dengan menu andalan: gudeg mercon yang pedesnya\nYang udah pada coba ndang absen lurrr\n\n#kulinermalam #kulinerjogja #gudeg #jogjafoodhunter #dyodoranjogja', '2023-10-03T09:28:23.000Z', 'Positif'),
(831, 'dyodoran', 'MENEMUKAN GRAND MASTER CHEF DI REMBANG!!\n\nKilas balik kulineran di Rembang, banyak yang menyarankan aku buat nyobain warung makan chinese seafood legendaris!\nInget pas main ke dapur liat proses masaknya yang WAAH... ini sih sekelas Master Chef!\nWarga Rembang ada yang tau tempat makan ini?\n\n#throwback #throwbackthursday #seafood #seafoodrestaurant #dyodoran', '2023-10-05T09:27:50.000Z', 'Positif'),
(832, 'dyodoran', 'Warmindo yang katanya pinya olahan mie instan terbaik, ratingnya sampe 4,9 di gmaps!\nBuka dari jam 16.00 - 04.00, Warga CCTV Semlidut Jogja ada yang udah coba?\n\n#warmindo #kulinerindonesia #kulinermalam #kulinerjogja #jogjafoodhunter', '2023-10-04T09:25:37.000Z', 'Positif'),
(833, 'dyodoran', 'Nyore ke Kulon Progo\nMampir ke bengkel VW @samgarageid yang dimana gak hanya nyervice tapi juga jual beli, sambil belajar tentang VW sama mas @and.vw \n\n#vw #vwbeetle #beetle #classicvw #superbeetle1302 #vwjogja #kulonprogo', '2023-10-05T01:54:26.000Z', 'Positif'),
(834, 'hobbymakan.id', 'Ide nya dari melamun aja, apa boleh semurah ini !\n\nPelopor mangkok bakso di jogja itu ternyata inspirasinya begini, mas @dyodoran kaget meronta2  !', '2023-10-08T04:27:10.000Z', 'Positif'),
(835, 'dyodoran', 'CUMA DI TEMPAT INI BISA MAKAN SEPUASNYA DAN MASIH DIKASIH DISKON 10%!!\n\nDalam rangka #haribatiknasional , @kakkoii_jogja kasih kalian DISKON 10% di tanggal 2 Oktober 2023.\n\nCatet S&Knya:\n\n1. Minimal kedatangan 2 orang.\n2. WAJIB RESERVASI melalui DM Instagram @kakkoii_jogja atau Whatsapp di +6282268355758.\n3. Follow Instagram @kakkoii_jogja dan mengisi Google Review.\n4. PROMO hanya BERLAKU di outlet KAKKOII JOGJA JALAN MAGELANG.\n\nSave, share dan buruan ajak temen kalian buat makan 140 menu sepuasnya lurrr\n\n#haribatiknasional #promoharibatiknasional #kakkoiijogja #kulinerjogja #jogjafoohunter', '2023-09-30T09:30:00.000Z', 'Positif'),
(836, 'dyodoran', 'HUJAN PROMO KULINER NUSANTARA SEPANJANG BULAN OKTOBER!!\n\n* 1 - 15 Oktober 2023: Voucher cashback 25k dengan minimal pembelian 80k, berlaku kelipatan, tidak dapat digabungkan promo lain.\n* 16 - 25 Oktober 2023: Promo ALL MENU Ayam Krispi + Es Teh hanya Rp. 18.182 + tax.\n*  25 - 31 Oktober 2023: Promo FREE Singkong Legit/ Singkong Garlic untuk setiap pembelian Iga Bakar.\n\nDengan promo sebanyak ini, selalu ada alasan buat makan enak, banyak, dan murah! Catet tanggal promonya, save dan share video ini ke teman kalian buat jadi referensi kuliner enak khas nusantara di Grand Indonesia ala @kedailocale . Follow instagramnya buat info lebih lanjut ya! \n\n#kulinernusantara #kulinerindonesia #kulinerjakarta #KedaiLocale #LidahLocale', '2023-09-29T09:30:00.000Z', 'Positif'),
(837, 'dyodoran', 'Mengisi weekend w/ mas Kenzie sang penakluk dunia\n\nTernyata bener apa yang di bilang temen2 “nanti cepet udah tengkurap lo mas Dyo” La kok beneeerrr sekarang lagi miring dan belajar tengkurep\n\n#bendyofamily', '2023-10-02T03:59:16.000Z', 'Netral'),
(838, 'dyodoran', 'Grebek kuliner pagi di Pasar Beringharjo!\nSebelumnya aku pernah mbahas Soto Bu Pudjo dan Soto Pak Muh too\nNah kali ini ada warung sate kere yang seharinya bisa habis sampai 45kg koyor! Wangun tenannn\n\nNdang share dan save video ini buat jadi referensi kuliner kalian lurr~\n\n#kulinerjogja #kulinerjogjamurah #jogjafoodhunter #dyodoran', '2023-10-23T09:34:10.000Z', 'Positif'),
(839, 'dyodoran', '\"Sajian mewah harga murah meriah\"\n\nMenurutku jadi istilah tepat buat warung mangut lele yang satu ini.\nDengan 20 ribu, kalian sudah dapat mangut lele, bakmie, pecel, dan nasi sebakul!\nMeskipun lokasinya tersembunyi di tengah pemukiman warga, tempatnya tetap asri, bersih, dan syahdu tenan lurr\nAda yang pernah coba?\n\n#mangutlele #hiddengemjogja #kulinerjogja #jogjafoodhunter #dyodoranjogja', '2023-09-23T09:30:00.000Z', 'Positif'),
(840, 'dyodoran', 'RENEW LAUNCHING PRODUCT SUSHI!\n\nMenu baru dan tampilan baru...\nBEST DEAL, 1 SET DAPET 4 SUSHI DAN 1 BAKED RICE!\n\nDimana lagii kalian bisa dapetin set menu ini selain di @shigerudeli ?!\n\nDan sekarang di Shigeru ada papan petunjuk dan label sesuai kategori sushinya, jadi kalian bisa pilih lebih cepat sesuai selera.\n\nApalagi buat yang belum pernah makan sushi, ada bagian khusus sushi matang yang wajib kalian coba!\n\nKarna packagingnya cantik, bisa sih healing sambil bawa sushinya. Kalo kalian kira-kira bakal bawa sushi ini kemana lur?\n\n#sushi #sushijogja #kulinerjogja #jogjafood #jogjafoodhunter', '2023-10-01T09:27:32.000Z', 'Positif'),
(841, 'dyodoran', 'Terpantau sampe terakhir aku dan @hobbymakan.id , pangsit gorengnya masih jadi rebutan karena digoreng dadakan!\nSiapa yang sering kehabisan?!\n\n#kulinerjogja #kulinerjogjamurah #jogjafood #jogjafoodhunter #jogjafoodies', '2023-09-24T09:28:28.000Z', 'Netral'),
(842, 'dyodoran', 'Dan terlihat gemashhh \n\n#bendyofamily #tasbayi #tas', '2023-09-23T03:10:25.000Z', 'Netral'),
(843, 'dyodoran', 'SATE BUMBU SANTEN?!\n\nJangankan kalian, aku pun kaget ketika dapat rekomendasi kuliner legendaris yang satu ini.\nBumbu sate serepeh ini dibuat dari campuran santen, cabe merah, dan bahan lainnya hingga menghasilkan kuah yang kental, lalu dilumuri ke daging ayam kampung yang sudah ditusuk dan dibakar.\nRasanya BEUH... semliduttt \nSelain sate serepeh, nasi tahu yang cuma 7000 juga wajib kalian coba lur!!\n\nInfo tempat dan ulasan selengkapnya bisa cek di Youtube Channel Dyodoran Playlist: Rembang.\n\n#sate #sateayam #kulinerlegendaris #kulinerindonesia #dyodoran', '2023-09-28T09:33:40.000Z', 'Positif'),
(844, 'dyodoran', 'Penasaran gak sih kalo lewat Stadion Mandala Krida di malam hari???\nRuamenya ampuuunnnn.... \nSiapa yang suka njajan ke siniii? \n\n#streetfood #siomay #kulinerjogja', '2023-10-08T04:27:15.000Z', 'Netral'),
(845, 'dyodoran', 'Menanggapi yang lagi rame tentang review jujur \n\nVideone di tonton sampe habis dulu ya biar infonya gak setengah2', '2023-09-27T04:28:33.000Z', 'Netral'),
(846, 'dyodoran', 'LEGENDA PERSATEAN PLERET, JUALAN DARI TAHUN 1950!\n\nDari info yang aku dapat, memang kalo kalian mau fokus ke kuliner persatean kambing dan sapi itu mainnya harus ke Jogja Selatan, terutama area Pleret & Imogiri.\n\nAda banyak warung sate berjejer yang legendaris, salah satunya warung ini!\n\nJualan cuma 5 jam dan sehari bisa ludes 10 kilo daging kambing yang rasanya BEUH.. semlidutt\n\n‌\nSelesai kulineran, langsung deh kalian ke Pakuwon Mall Jogja karena akan ada Pameran Cat Terbesar dan Termurah se-DIY dan Jateng tanggal 27 September - 1 Oktober 2023 dari @tokocatlancar_id . Kalian juga bisa dapet DISKON up to 70%, Temu Artis dan Nonton Konser GRATIS TIS TIS!! Semuanya cuma ada di Event Lancar Paint Expo 2023, Urusan Cat, Pasti Lancar!\n\n#Lancarpaintexpo2023 #UrusanCatPastiLancar #pamerancatterbesardiDIYJateng #kulinerjogja #jogjafoodhunter', '2023-09-25T09:27:18.000Z', 'Positif'),
(847, 'dyodoran', 'SPOT MAKAN SIANG BARENG WARGA SEKAMPUNG!\n\nWarung ini lokasinya emang di daerah perumahan dan menurutku cocok buat tempat rapat acara RT, apalagi harga menunya mulai dari 18 ribuan!\n\nSpesialis di menu bebakaran dan kalian harus cobain Bebek Bakar Mercon yang pedesnya nendang dengan sentuhan rasa manis kecap yang khas!\n\nMenu Ikan Gurame dan Nilanya juga rekomendid karena ikannya fresh langsung diangkat dari kolam\n\nBisa delivery order atau pesen secara online juga yaa\n\nNdang follow IG @pojokbebakaran untuk info promo tiap harinya!\n\n#kulinerjogja #kulinerjogjamurah #jogjafood #jogjafoodhunter #dyodoranjogja', '2023-09-26T09:28:57.000Z', 'Positif'),
(848, 'dyodoran', 'Salah satu soto top list yang wajib kalian coba kalo lagi di Jogja!\nKalo aku dan Mas Evan @hobbymakan.id pilih makan di trotoar sambil menikmati suasana pagi Jogja\nKalo kalian pilih makan dimana lur?\n\n#soto #sotoayam #kulinerjogja #kulinerlegendaris #jogjafoodhunter', '2023-09-22T09:30:00.000Z', 'Positif'),
(849, 'dyodoran', 'MENU HEMAT MODE AKHIR BULAN!!\n\nCuma di @buburhayam , dengan 10 RIBU kalian bisa dapet Bubur Hayam & Teh!\n\nKalo mau manis ya langsung pesen Bubur Ketan Hitam Spesialnya yang gak pernah salah buat dinikmati di tengah teriknya cuaca Jogja.\n\n2 Secret Menus nya jangan sampe lewat!\n\nBayangin Es Milo dan Jus Mangga yang manis dan seger dikasih extra ice cream, diaduk merata terus cegluk cegluk… meluncur ke kerongkongan yang kering kerontang\n\nNgiler to?? Makanya buruan ajak temen dan keluarga kalian ke @buburhayam atau hubungi via DM Instagram untuk pemesanan partai besar!\n\n#buburhayam #kulinerjogja #kulinerjogjamurah #jogjafoodies #jogjafoodhunter', '2023-09-21T09:26:25.000Z', 'Positif'),
(850, 'dyodoran', 'MELAYANI LAMBUNGMU SEPENUH HATI, MULAI HARGA 10-17 RIBU AJA! JAYA JAYA JAYA!\n\nPelopor Nasi Genjes No. 1 di Indonesia akhirnya buka di Jogja lurr\n\nIni tuh beberapa kali masuk FYPku dan akhirnya aku paham kenapa ini viral pol!\n\nPertama, harganya jelass terjangkau dan kita juga bisa beli lauknya tok mulai dari 4 ribu\nKedua, porsinyaaa ampun.. Bener-bener membahagiakan lambung!\nKetiga, ini tuh bukanya dari jam 17.00 - 01.00, menambah pilihan kuliner malam kalian!\n\nDari 3 menu yang aku cobain, aku paling suka Nasi Genjes Cakalang Sambel Matah dan Es Setrup buat bantu ngilangin pedesnya!\n\nAku makan di @wrg.mekarjaya dan ada 1000 PORSI GRATIS sampe tanggal 20 September 2023. Ndang diserbu lurrr\n\n#kulinerjogja #kulinerjogjamurah #jogjafood #jogjafoodhunter #jogjafoodies', '2023-09-18T09:28:16.000Z', 'Positif'),
(851, 'dyodoran', 'Dawet legend termurah yang pernah aku temuin bareng Mas @hobbymakan.id !\nPas banget diminum di tengah cuaca jogja yang lagi puanas puanasnyaaaa\nLokasinya ada di deket kampus PGRI, kalian ada yang pernah coba?\n\n#kulinermurah #jajanmurah #esdawet #kulinerjogja #kulinerjogjamurah', '2023-09-16T09:27:59.000Z', 'Positif'),
(852, 'dyodoran', 'Jus buah suegerrr yang porsinya ugal ugalan!!\nMenurutku ini best deal apalagi buat kalian yang lagi diet, bisa sekalian nyetok iki lurr\nKalian ada yang langganan di sini juga gak?\n\n#jus #jusbuah #jusbuahsegar #kulinerjogja #kulinerjogjamurah', '2023-09-20T09:26:10.000Z', 'Positif'),
(853, 'dyodoran', 'Jogja identik dengan kulinernya yang muuuwwwraahhh!\nSalah satunya mie ayam balungan ini yang bisa kalian coba dengan modal 8 ribu aja!\nMas Evan @hobbymakan.id kemaren coba porsi normal, nek aku ya pasti porsi jumbo to yoooo wgwgwg\nKalo kalian kira-kira bakal pesen porsi apa ki lur?\n\n#mieayam #mieayambakso #mieayamjogja #mieayambalungan #kulinerjogja', '2023-09-12T12:21:39.000Z', 'Positif'),
(854, 'dyodoran', 'Rawon identik sebagai salah satu kuliner khas Jawa Timur.\nTapii pas trip Youtube ke Rembang, Warga CCTV Semlidut Rembang menyarankan aku buat coba rawon di sini dan rasanya BEUH... sensasi manis khas kuliner Jawa Tengah langsung terasa di lidah!\nTerakhir aku ke sini sih harga seporsi Nasi Rawon cuma 9.000, jadi wajib buat kalian coba karena terjangkau pol lurrr\n\n#throwback #throwbackthursday #rawon #kulinerlegendaris #kulinerindonesia', '2023-09-14T09:42:31.000Z', 'Positif'),
(855, 'dyodoran', 'Pecinta angkringan murah merapat, aku nemu gorengan yang harganya mash 500 perak!!\nAda juga sego kucing, bihun, dan nasi rames dengan harga maksimal 5000! MAKSIMAL lho yoooo\nTertarik? Makanyaa tonton dulu ulasan selengkapnya di Channel Youtube Dyodoran\n\n#angkringan #angkringanjogja #kulinerjogja #kulinerjogjamurah #jogjafoodhunter', '2023-09-17T09:28:24.000Z', 'Positif'),
(856, 'dyodoran', 'Sebenernyaa ini kuliner sederhana yang pasti ada juga di kota kalian\nTapiii proses masaknya yang unik bikin tahu in jadi salah satu jajanan rekomendasiku dan mas Evan @hobbymakan.id ! \nAda yang pernah coba?\n\n#gorengan #tahu #tahugoreng #kulinermurah #kulinerjogja', '2023-09-19T09:40:52.000Z', 'Positif'),
(857, 'dyodoran', 'NONGKRONG, METIK SAYUR, KASIH MAKAN RUSA DAN IKAN DALAM 1 TEMPAT!!\n\nInfo infooo, aku punya tempat healing all in one BARU!\n\nLuas lahannya 5 hektar dengan beragam fasilitas yang seru! Mulai dari metik sayur organik, serta kasih makan ikan dan rusa! Kalian bisa bikin acara outing atau gathering juga lhoo\n\nTersedia paket Udang Telor Asin, Capcay + Es Teh seharga 35 ribu, atau beli ala carte mulai dari 12 ribuan, kopi mulai dari 15 ribuan!\n\nNgerjain tugas anti mumet dengan free WiFi dan pemandangan Merapi yang ciamik, jangan lupa beli sayur organik yang cuma 6 ribu per ikat. Best deal iki lurr\n\nBuka dari jam 06.00 - 18.00, ndang ajak temen temen kalian ke @nara_kupu_jogja !\n\n#narakupujogja #narakupuvillage #sayurorganik #kulinerjogja #jogjafoodhunter', '2023-09-15T09:28:50.000Z', 'Positif'),
(858, 'dyodoran', 'Spot nyoto yang unik dengan sate satean terlengkap yang pernah aku temuin!\nWarga CCTV Semlidut Jogja ada yang pernah ke sini?\n\n#soto #sotoayam #kulinerjogja #jogjafoodhunter #dyodoranjogja', '2023-09-13T09:28:23.000Z', 'Positif'),
(859, 'dyodoran', 'Sejauh ini, warung ini jadi warung spesialis mangut lele duri lunak tertua yang pernah aku datengin!\nBerjualan sejak tahun 1930an, seharinya mereka bisa jual 500 ekor mangut lele dengan bumbu yang BEUH... semliduttt\n\n#mangutlele #kulinerlegendaris #kulinerjogja #jogjafoodhunter #dyodoranjogja', '2023-09-11T09:25:10.000Z', 'Positif'),
(860, 'dyodoran', 'AKHIRNYA BUKA CABANG!!\n\nAda banyak warung nasi goreng sapi/ nasi goreng kambing di Jogja, dan ini dia pelopornya!\nNasi goreng di sini punya ciri khas rempah yang luget, nasi yang meprel dann potongan daging yang melimpah! Jadi tiap sendokan tuh rasanya semlidut lezatos kotos kotos mbledosss\n\nDetail lokasi ada di akhir video, ndang ajak temenmu ke sini lurrr\n\n#nasigoreng #nasigorengkambing #kulinerjogja #jogjafood #jogjafoodhunter', '2023-10-02T09:28:14.000Z', 'Positif'),
(861, 'dyodoran', 'TAKUT BANGET KALO MAKAN DI SINI...\n\nPas makan Nasi Gandul di Pati, jujur aku takut pas makan..\nMaksudnya takut cepet habis, karena seporsi nasi gandul dengan daging yang berlimpah ini harganya cuma 16 ribu rupiah!\nInget makannya tuh pelan-pelan karena kuahnya yang luget sungguh nikmat, semliduttt\nWarga CCTV Semlidut Pati ada yang pernah makan di sini?\n\n#throwback #throwbackthursday #kulinerpati #kulinerlegendaris #dyodoran', '2023-09-07T09:34:07.000Z', 'Positif'),
(862, 'dyodoran', 'Jogja selalu punya kejutan di setiap jenis kulinernya—termasuk yang satu ini!\nInovasi menu mie nyemek kuah padang menghasilkan mie nyemek berbumbu luget yang sulittt untuk kalian tolak!\nBener gak Mas Evan @hobbymakan.id ??\nWarga CCTV Semlidut Jogja sudah ada yang coba? \n\n#mie #mienyemek #kulinerjogja #jogjafood #jogjafoodhunter #dyodoranjogja', '2023-09-04T09:30:00.000Z', 'Positif'),
(863, 'dyodoran', 'PERTAMA KALI NEMU NASI BEBEK YANG BUKA PAGI!!\n\nOverall bebeknya gurih dan empuk pol, patut diapresiasi!\n\nHabis sat set sarapan, lanjut berkegiatan ngedit, VO dan kejar deadline lainnya.\n\nProses kerja juga tetap sat set karena aku pake jaringan internet dari Indihome yang sudah bergabung sama Telkomsel, jadi koneksinya lebih kuat!\n\nBuat pengguna baru, saranku pilih Paket JITU 1 - 1P karena dengan harga 200 ribuan, kalian sudah dapat kecepatan hingga 40 Mbps termasuk langganan Disney+ Hotstar!\n\nFollow @indihome dan @telkomsel untuk info berlangganan selengkapnya!\n\n‌\n\n#BergerakMelajuBersama #DariRumahTanpaBatas #nasibebek #kulinerjogja #jogjafoodhunter', '2023-09-08T09:30:00.000Z', 'Positif'),
(864, 'dyodoran', 'pecinta bakso wajib merapat, aku punya - spot bakso halus yang semlidut!!\nini tipe bakso halus yang membel, tapiti pas digigit BEUH... mak kres, memanjakan lidah!\n\n#bakso #baksosapi #baksohalus #kulinerlegendaris #kulinerjogja', '2023-09-09T09:30:00.000Z', 'Positif'),
(865, 'dyodoran', 'SATU SATUNYA PIZZERIA YANG PUNYA PABRIK KEJU SENDIRI DI JOGJA!\n\nKalo kalian ada acara spesial dan mau makan pizza otentik, tempat ini jawabannya!\n\nMenu baru Pizza Stellata ini dibuat dari bahan premium, keju mozzarella dan ricottanya diproduksi sendiri dan kalian bisa lihat proses pake tungku yang dibikin langsung sama orang Italia!\n\nSetiap sudut tempat ini instagramable pol dan kalian sudah dapat FREE fotografer tanpa minimal pembelian, jadi jangan lupa foto-foto yaa wgwgwg\n\nDari menu yang aku makan, saranku sih kalian coba.. semuanya aja karena sudah terverifikasi semlidut lezatos kotos kotosss\n\nFollow IG @giornopizzeria.id buat info selengkapnya!\n\n#giornopizzeria #italianpizza #kulinerjogja #jogjafoodies #jogjafoodhunter \n\n‌\n\nreels', '2023-09-02T09:30:00.000Z', 'Positif'),
(866, 'dyodoran', 'MUNGKIN INI SAT SATUNYA DI JOGJA...\n\nKalo kalian follow aku dari lama, kalian pasti tau aku udah mbahas belasan-puluhan gudeg di jogja dan sejauh ini, aku pertama kalinya nemu kluwo di sini! \nMenurutku, semua menunya semlidut dan ini bukan tipe gudeg manis, jadi rekomendit buat kalian yang dari luar kota!\n\n#gudeg #gudegjogja #gudegceker #kulinerlegendaris #dyodoranjogja', '2023-09-05T09:30:00.000Z', 'Positif'),
(867, 'dyodoran', 'Kalo kalian lagi main ke daerah Jogja Kota di tengah siang bolong dan mau yang seger-seger kayak aku dan mas @hobbymakan.id , ini dia jawabannya!\nSelain legend, cuma di sini kalian bisa temuin es buah dengan sawo tiap hari! Semliduttt \n\nSave & share postingan ini biar kuliner kalian gak itu itu aja lur wgwgwg\n\n#esbuah #kulinerlegendaris #kulinerjogja #dyodoranjogja', '2023-09-03T09:30:00.000Z', 'Positif'),
(868, 'dyodoran', 'Sejauh ini, ini nasi bebek termurah yang pernah aku temuin\nSelain murah, warung nasi bebek ini BUKA 24 JAM!\nRasanya pun patut diapresiasi!!\nWarga Jogja Selatan ada yang pernah coba?\n\n#nasibebek #nasibebeksurabaya #kulinerjogja #jogjafoodhunter #dyodoranjogja', '2023-08-29T12:00:00.000Z', 'Positif'),
(869, 'dyodoran', 'Kalo kalian mau nyobain sensasi sate klathak yang beda, kalian wajib cobain sate klathak di sini!!\nKuah tongsengnya yang luget dan gurih BEUH.. semlidut lezatos kotos kotosss\n\n#sateklatak #kepalakambing #mukbang #kulinerjogja #dyodoranjogja', '2023-09-01T09:29:36.000Z', 'Positif'),
(870, 'dyodoran', 'PROMO BUY 1 GET 1 DI RESTORAN AQUASCAPE CIAMIK BARU SETIAP HARI!\n\nMenurutku tempat ini bener-bener memanjakan mata lelah dengan konsep aquascapenya yang ciamik + nyegerin!\n\nNah promo Buy 1 Get 1nya berlaku untuk V60 Aceh Gayo, V60 Mandailing, Rosberry Wish, Melcherry Blossom! Kapan lagi modal 30 ribu bisa dapet 2 minum?!\n\nMenu-menu yang disajikan beragam, mulai dari menu nusantara sampai western! Kalo kalian dateng pagi, saranku pesen Bubur Ayam Natura dan pilih healthy jusnya, semlidutt\n\nTersedia ruangan outdoor dan indoor yang sejuk, serta area parkir yang luas. Buka dari jam 7.00 - 23.00, cocok buat kalian para tim #workfromcafe atau makan-makan bareng keluarga.\n\nFollow IG @naturadiningbynature untuk info promo selengkapnya!\n\n#naturadiningbynature #finedining #kulinerjogja #jogjafood #jogjafoodhunter', '2023-09-06T09:30:00.000Z', 'Positif'),
(871, 'dyodoran', 'BUMBUNYA ASAL-ASALAN, YANG PENTING ENAK!!\n\nKilas balik kali ini aku mau ajak kalian ke Wonogiri untuk mengingat betapa nikmatnya pindang kambing Mbok Sinem\nKuliner ini sudah berdiri sejak tahun 1988, dan pas aku tanya bumbu yang dipake ternyata.. Simbahnya pake bumbu asal-asalan aja, yang penting enak!\nSelain enak, pindang ini juga murah meriah lurrr, seporsinya cuma 5000 rupiah!\nWarga CCTV Wonogiri ada yang pernah coba?\n\n#pindangkambing #kulinerlegendaris #kulinerwonogiri #kulinerindonesia #dyodoran', '2023-08-31T09:30:00.000Z', 'Positif'),
(872, 'dyodoran', 'SALUT! WARUNG INI HANYA FOKUS PADA 1 JENIS MASAKAN SEJAK TAHUN 70an\n\nKalo kalian ke warung Bakmi Jawa, biasanya ada menu selain bakmi kayak nasi goreng, nasi godhog, kwetiaw, dan sebagainya TAPIII di sini beda!\nPak Sartugi fokus pada 2 menu: bakmi godhog dan bakmi goreng tok.\nTipikal bakminya pipih kecil, dengan cara masak yang beda sehingga aroma kaldu ayamnya BEUH... nampol!!\nAku ke sini 2 tahun lalu dan harga per porsinya cuma 10ribu. Kalo sekarang jadi harga berapa ya?\nWarga Karanganyar boleh dongg komen di bawahh\n\n#throwback #throwbackthursday #bakmi #bakmijawa #kulinerkaranganyar', '2023-08-24T09:30:00.000Z', 'Positif'),
(873, 'dyodoran', 'Mbahas kuliner malam pasti gak lengkap kalo gak nyebut gudeg yang satu ini.\nJualan dari jam 8 malam - jam 1 pagi, tiap harinya ludes 50 kg nasi!\nKebayang kan enak dan ruamenya kayak apa?? \n\nUlasan selengkapnya ada di Youtube Channel Dyodoran yaa\n\n#gudeg #kulinermalam #kulinermalamjogja #kulinerlegendaris #jogjafoodhunter', '2023-08-25T09:30:00.000Z', 'Positif'),
(874, 'dyodoran', 'PERTAMA KALI MAKAN BURGER RASA MIRIP WASABI!!\n\nKalo biasanya saus burger identik dengan rasa tomat, keju, atau barbeque, saus burger disini beda karena terasa mirip wasabi\n\nTernyata sausnya dibuat dari mayonnaise kacang polong! Terus ada rucola, sayur yang kaya akan zat besi, vitamin A dan C dengan karakter rasa yang kuat dan sedikit pedas! Gokilnya, ini vegetarian burger loh! Kira-kira pattynya dari apa ya?\n\nPenasaran kan.. makanya, ndang cobain burger ini dan menu-menu sehat lainnya dari @wakeupsaam ! Terverifikasi semlidut lezatos kotos kotoss\n\n#wakeupsaam #finestbreakfast #jogjafood #jogjafoodies #kulinerjogja', '2023-08-22T09:37:27.000Z', 'Positif'),
(875, 'dyodoran', 'Pertama sampe Jogja langsung kita kasih yang heboh @hobbymakan.id', '2023-08-27T05:17:46.000Z', 'Positif'),
(876, 'dyodoran', 'Ini tuh kuliner otentik Bali yang udah jadi langganan temen-temenku\nPas aku cobain rasa pedesnya BEUH.. NAMPOOLL!! \nOiya, semua kuliner di sini halal yaa, ndang dicoba lurrr\n\n#nasijinggo #kulinerkhasbali #kulinerjogja #jogjafoodhunter #dyodoranjogja', '2023-08-20T09:30:00.000Z', 'Positif'),
(877, 'dyodoran', 'Kilas balik sate legendaris di dalam pasar!!\n\nIni persatean yang direkomendasikan sama Warga CCTV Semlidut\nSudah dijalani generasi ke 4, lokasinya di dalam Pasar Kota Sragen\nMeskipun di dalam pasar, pengunjungnya ruame pol lurrrr!!\n\nSave dan share postingan ini buat jadi referensi kuliner kalian yaaw\nUlasan selengkapnya ada di Youtube Channel Dyodoran, Sate Pak Jamin \n\n#satekambing #satesapi \n#kulinersragen #kulinerlegendaris #kulinerindonesia', '2023-08-17T09:27:26.000Z', 'Positif'),
(878, 'dyodoran', 'TAU GAK ADA ALL YOU CAN EAT SUSHI DAN SASHIMI DI JOGJA?!\n\nJujur aku baru pertama kali makan di sini dan setiap menunya BEUH… premium, wenakkk dan semlidut lezatos kotos kotos! \n\nTersedia 3 varian paket ayce MULAI DARI 99 RIBU dan menu ala carte dengan bahan yang bener-bener fresh! \n\nTempatnya luas, instagramable, sejuk, cocok buat kumpul bareng keluarga atau temen-temen kalian\n\nAda banyak promo selama bulan Agustus! Follow @sushihasha buat info lebih lanjut yaww\n\n#sushi #sashimi #aycesushi #kulinerjogja #jogjafoodies', '2023-08-18T09:28:42.000Z', 'Positif'),
(879, 'dyodoran', 'Spot perkambingan yang satu ini berdirinya belum terlalu lama TAPIII dalam waktu 4 jam, stok 200kg kambing ludes!!\nLokasinya ada di Bantul. Kalian ada yang udah ke sini?\n\n#satekambing #kambing #kulinerjogja #jogjafoodhunter #dyodoranjogja', '2023-08-19T09:30:00.000Z', 'Positif'),
(880, 'dyodoran', 'Pertama kali nyobain ice cream setinggi ini dengan cone dari croissant!\nLokasinya pas di pertigaan dan ruame pol lurrr\nKalian ada yang pernah coba gak?\n\n#icecream #icecreamcone #kulinerjogja #jogjafood #jogjafoodhunter', '2023-08-26T09:24:46.000Z', 'Positif'),
(881, 'dyodoran', '30 TAHUN JADI SUPPLIER MIE, AKHIRNYA BUKA WARUNG SENDIRI!!\n\nKabar baik buat pecinta mie ayam, ada spot mie ayam & bakso khas Wonogiri baru nih!\nMienya dibuat sendiri, semur ayamnya manis berempah, tekstur baksonya makkres BEUH... semlidutt\nKalo mau pesen mie basah buat jualan mie ayam juga bisa. Dikirim sampai lokasi lur!\n\nMie Avam Bakso Pak Agus Arga \"Asli Wonogiri\"\nLokasinya pas di Utara Bangjo Blok O, samping pintu masuk RSPAU Hardjolukito!\nNdang mrene yooo~\n\n#mieayam #mieayambakso #mieayamjogja #kulinerjogja #jogjafood', '2023-08-21T09:30:00.000Z', 'Positif'),
(882, 'dyodoran', 'Di Jogja tuh gak banyak yang jual gudeg manggar\nNah uniknya pas dulu main ke Keraton aku juga dapet suguhan ini!\nKalian ada yg pernah coba?\n\n#gudeg #gudegmanggar #gudegjogja #kulinerjogja #dyodoranjogja', '2023-08-13T12:03:05.000Z', 'Positif'),
(883, 'dyodoran', 'MUKBANG SEGO BANCAKAN KHAS SUNDA PORSI BRUTAL!!\n\nYang aku makan tuh sebenernya porsi buat 7 orang tapi tak makan sendirian wgwgwg wareg puol!!\n1 paket ini sudah termasuk Ayam Goreng Kampung, Tumis Cumi Asin Cabe Ijo, Sayur Asem dan beberapa lauk lainnya\nKalian bisa pilih mau paket nasi tutug tempe kayak aku atau nasi liwet\n\nSelain sego bancakan, kalian juga wajib pesen Sup Iga dan Iga Bakarnya lurr\nDitemani dengan pemandangan di @supigarindualam yang seindah ini, definisi melepas kepenatan di kota~\n\n#supigarindualam #segobancakansundajogja #masakansundajogja #kulinerjogja #jogjafoodies', '2023-08-15T09:30:00.000Z', 'Positif'),
(884, 'dyodoran', 'HIDDEN GEM SALAD BAR DI JALAN PALAGAN!!\n\nKalo lagi ga syuting, aku selalu biasain detox pencernaan dengan makan sayur sayuran biar ga buncit wgwgwg\nNah kali ini kebetulan aku nemuin hidden gem persalad-tan yang joss!!\nYang kupesen namanya Grill Chicken Salad yaw\nKalian ada yg pernah kesini juga gak?\n\n#salad #saladjogja #kulinerjogja #jogjafoodies #dyodoranjogja', '2023-08-09T09:25:31.000Z', 'Positif'),
(885, 'dyodoran', 'CUMA DI SINI BELI MAKAN MALAH DAPET 100RIBU!!\n\nIni tuh kuliner yang udah aku makan dari jaman kuliah, jadi pas mbalik kesini serasa nostalgiaa hehehe\n\nBtw info nihh, kalian bisa pesan makan lebih mudah dan murah lewat aplikasi @jogjakita_official dengan claim Bonus Poin 100ribu dan dapetin diskon 20% untuk check out kuliner favoriitmu! buat followersku ada harga khusus yaaa sampai akhir bulan Agustus ini\n\nAda juga fitur video sharing, jadi ndang install dan follow akun Dyodoran di aplikasi JogjaKita lurr\n\nKira-kira kalian bakal check out menu apa nih dari @bungongjeumpajogja ? \n\n#jogjakita #kulinerjogja #jogjafoodies', '2023-08-11T09:25:06.000Z', 'Positif'),
(886, 'dyodoran', 'SOTO DENGAN TOPPING JEROAN LENGKAP DI SRAGEN!!\n\nKilas balik sore ini aku mau ajak kalian kulineran ke Sragen.\nIni tuh soto legendaris yang sudah berdiri sejak 1953 dengan harga per porsi CUMA 9000!!\nYang bikin seneng, topping jeroannya lengkap lurrr\nMulai dari babat, iso, paru, limpa, lidah... BEUH... bikin ngilerrrr\nWarga CCTV Semlidut Sragen ada yang pernah ke sini gak??\n\n#throwback #throwbackthursday #kulinersragen #kulinerlegendaris #dyodoran', '2023-08-10T09:26:25.000Z', 'Positif'),
(887, 'dyodoran', 'info kuliner perbebekan di jogja selatan!!\nkalian ada yg langganan di sini gak lur?\n\n#nasibebek #nasibebekjogja #kulinerjogja #jogjafoodies #dyodoranjogja', '2023-08-08T09:30:00.000Z', 'Positif'),
(888, 'dyodoran', 'ini tuh soto terbanyak topping, terlaris, terpagi yang pernah aku datengin wgwgwg soalnya nek kesiangan dikit ya bablas lurrr\nkalian udah ada yg berhasil makn disini belum? \n\n#soto #sotosapi #kulinerlegendaris #kulinerjogja #dyodoranjogja', '2023-08-05T09:57:58.000Z', 'Positif'),
(889, 'dyodoran', 'MUKBANG KAMBING GULING UTUH!! \n\nMbalik lagi ke sini buat kasih info lengkap tentang perkambingan yang satu ini!!\nSudah tayang di Youtube Channel Dyodoran yaww, ndang ditonton lurr~\n\n#kambingguling #satekambing #kulinerklaten #klatenkuliner #dyodoran', '2023-08-06T09:27:46.000Z', 'Positif'),
(890, 'dyodoran', 'akhirnya keturutan nyobain ikan cipung \nkalian ada yang udah coba? suka enggak?\n\n#ikan #ikancipung #izakaya #izakayajogja #kulinerjogja', '2023-08-07T09:30:00.000Z', 'Positif'),
(891, 'dyodoran', 'DITANTANG MUKBANG KAMBING❌\nDITANTANG MASAK KAMBING✅✅✅\n\nKaget pol pas di acara @finnafood_id kemarin, karena aku dapet Mystery Box berisi KAMBING!!\nUntung kuliner perkambinganku lumayan, jadi bisa sat set masak bareng 120 peserta lainnya!!\n\nMomen paling dag dig duar tuh pas penilaian sih, karena ada @inijie , Chef @rinrinmarinka dan juri-juri keren lainnya!\n\nSelain ikut lomba masak, aku juga explore bazar UMKMnya.\nSeneng deh bisa ketemu banyak temen-temen di sini!!\n\nSampai ketemu di acara Finna Foodies Competition 2024 lurrr\n\n#finnafoodiescompetition #finnafoodiescompetition2024 #prambanan', '2023-08-14T09:30:00.000Z', 'Positif'),
(892, 'dyodoran', 'SATU SATUNYA STEAK YANG DIPANGGANG DENGAN KOMPOR PLAT BAJA!!\n\nTapi ini bukan sembarang kompor ya lurr.\nNamanya plancha grill, pemanggang plat baja yg diimpor langsung dr Argentina!\n\nDengan metode memasak klasik \"wood-fire a la plancha\" dgn suhu 300 derajat celcius,steak yang dihasilkan BEUH... jauh lebih juicy dan smoky!! \nSatu-satunya steakhouse di hotel Jogja dgn metode memasak ini! \n\nKita bisa menyaksikan langsung proses memasaknya & berinteraksi langsung dgn master grill-nya.\n\nBtw ada PROMO nih: \n- 3 Course Steak Dinner IDR 350.000 net/pax: appetizer, steak, dessert, mocktail. Pilihan daging: tenderloin, sirloin, dan ribeye\n- Steak & Grill Dinner Set IDR 1.675.000, paket utk sharing 4-6 orang: wagyu, sosis, salmon, bebek, lengkap dengan potato & assorted vegetables\n\nDetail menu & reservasi langsung follow Instagram @naiclasteak yaww\n\n#steak #steakhouse #naiclasteak #naiclasteakandgrill #gaiacosmohotel #kulinerjogja #jogjafooddestination', '2023-08-04T09:27:21.000Z', 'Positif'),
(893, 'dyodoran', 'AKHIRNYA NYOBAIN MAKAN DI WARUNG TENDA ALA DRAKOR!\n\nKalian pasti nemuin warung ini di drakor manapun dan kemecer pengen nyoba, ya tooo??\n\nNah ini warung tenda alias pojangmacha rekomendasiku di Jalan Kaliurang.\n\nHarganya mulai dari 8ribuan dan semua menunya HALAL, no pork, no lard, no alkohol! Porsinya juga bikin kenyang\n\nMeskipun tendaan, makan di sini tetap nyaman karena ada ACnya dan tersedia juga baby chair. CATET jam bukanya ya: Senin-Kamis dari jam 15.00-22.00, Jumat-Minggu dari jam 15.00-24.00.\n\nFollow @noldapocha untuk info promo dan lainnya lurr\n\n#noldapocha #noldapochajogja #koreanstreetfood #jogjafoodies #kulinerjogja', '2023-08-30T09:24:44.000Z', 'Positif'),
(894, 'dyodoran', 'KU KIRA BEBEK BACEM, TERNYATA...\n\nternyata gak cuma dimasak bacem, kalian juga bisa request buat diopor, digoreng, atau rica rica!!\nmuantep polll\nWarga CCTV Semlidut Magelang ada yang pernah coba?\n\n#bebek #bebekgoreng #kulinermagelang #dyodoran', '2023-07-29T09:30:00.000Z', 'Positif'),
(895, 'dyodoran', 'ALASAN KENAPA KAMU HARUS KULINERAN DI JOGJA, NOMER 3 GAK MASUK AKAL!!\n\nGak masuk akal karenaaa dimana lagi kalian bisa menikmati opor bebek mulai dari harga 9 ribu?!\nAtau makan sate klathak sampai kenyang, karena seporsi cuma 22ribu dan sudah dapat 4 tusuk??\n\nMari cintai, beli, dan konsumsi produk dalam negeri serta menangkan hadiah total Rp10 juta dengan ikut Kompetisi Video Flexing Lokal dari Kemenkopukm X Google dan Youtube!!\n\nInfo selengkapnya cek di instagram @kemenkopukm dan @googleindonesia yaa, ditunggu sampai 4 Agustus 2023 lurr\n\n#FlexingLokal #barengGoogledanYoutube #BanggaBuatanIndonesia #HariUMKM2023', '2023-08-01T09:25:57.000Z', 'Positif'),
(896, 'dyodoran', 'kemaren pada nanyain lokasi dan rasa dari kuliner yang satu ini too\njadi ndang tonton ulasan selengkapnya di Channel Youtube Dyodoran!! \n\n#nasihainam #nasihainan #kulinerjogja #jogjafoodhunter #dyodoranjogja', '2023-08-02T09:26:59.000Z', 'Positif'),
(897, 'dyodoran', 'Udah weekend ajaaaaaaa \nPada mampir ya ke @tokosemlidut oleh-oleh Jogjanya aku , Atau bisa kirim ke penginapan WA Aja  0818-0789-9499 \n\n#tokosemlidut #oleholehjogja #kulinerjogja #jogja', '2023-07-28T03:04:08.000Z', 'Positif'),
(898, 'dyodoran', 'Kalo kalian ke Jogja dan turn di Pasar Lempuyangan jam 6-an, saranku kalian sarapan tongseng kambing ini lurr \nTongseng kambing ini beda karena rasanya BEUH.. dan per hari cuma stok 40 porsi padahal banyak yang cari!!', '2023-07-24T09:30:00.000Z', 'Positif'),
(899, 'dyodoran', 'MUKBANG SUSHI HALAL 10 RIBUAN!!\n\nAkhirnya @shigerudeli buka cabang kedua di Jogja!\nAda promo sushi 10 RIBUAN dan BUY 1 GET 1 free drink yang berlaku sampai 11 Agustus 2023!\nSelain sushi, kalian juga wajib cobain spicy odeng, tempura dan robatayakinya\nSemlidut lezatos kotos kotosss \n\n#sushi #sushihalal #shigeru #kulinerjogja #kulinerjogjamurah', '2023-07-31T04:41:45.000Z', 'Positif'),
(900, 'dyodoran', 'PEDES MBLEDOS GOBYOS GOBYOS!!\n\nKilas balik kali ini aku mau ajak kalian ke Sragen!\nPas di timur Jembatan Gawan, ada warung bothok legendaris yang sudah buka sejak tahun 1980an\nMenu sih cuma ada Bothok Ayam & Patin ya pas aku dateng tapii rasanya BEUH... semlidut lezatos kotos kotosss\nWarga CCTV Semlidut ada yang pernah coba?\n\n#throwback #throwbackthursday #kulinersragen #kulinerlegendaris #dyodoran', '2023-07-27T09:26:20.000Z', 'Positif'),
(901, 'dyodoran', 'Ini tuh salah satu gudeg legendaris yang memang gak diomongin\nsemua orang\nExperience untuk intip dapur, antri ambil makan dan antri buat dapet tempat duduknya juga gak bakal terlupakan furrr wgwgwg\nKalian ada yang pernah kesini gak?\n\n#gudeg #kulinerlegendaris #kulinerjogja #jogjafood #dyodoranjogja', '2023-07-26T09:59:29.000Z', 'Positif'),
(902, 'dyodoran', 'KARE PERTAMA DI KARANGANYAR!!\n\nAku mau ajak kalian kilas balik ke kuliner legendaris Karanganyar yang masih super tradisional!!\nKuliner ini sudah masuk generasi ke 3 dan proses masaknya masih pakai kuali.\nAlat pikul yang dipakai tahun 1960-an pun masih dipakai juga sampe sekarang dan ini adalah kare ayam pertama di Karanganyar.\nNamanya Kare Mbah Setu, ada yang pernah coba?\n\n#throwback #throwbackthursday #kulinerlegendaris #kulinernusantara #dyodoran', '2023-08-03T09:29:54.000Z', 'Positif'),
(903, 'dyodoran', 'Selamat pagi kaum begadang \nYang paginya merem anaknya melek \nNgantukkk beraaaaaattttzzzzzzz…\n\n#newborn #bendyofamily', '2023-07-24T02:58:31.000Z', 'Netral'),
(904, 'dyodoran', 'warung ramesan yang lagi viral di jogja!! \nsatu catetan dari aku: hati hati dijotos karo sambele @kantinlarasati lurrrr\n\n#warteg #kulinerjogja #jogjafood #jogjafoodhunter #dyodoranjogja', '2023-07-23T09:30:00.000Z', 'Positif'),
(905, 'dyodoran', 'HIDDEN GEM PRIVATE DINNER 100% HALAL DI TENGAH KOTA JOGJA!!\n\nDengan spesialisasi menu peranakan chinese melayu yang dikembangkan sama momicep @casademiakitchen , menu di sini lebih kaya bumbu dan terjamin 100% HALAL!\n \nNah karena konsepnya private dinner dan cuma buka Kamis-Minggu dari jam 17.00 - 21.00. , kalian WAJIB reservasi sebelum datang!\nSekalian pesen menu ya..\n\nNama tempatnya BUKA MEJA Cemorojajar by Casademia Kitchen\nInfo lebih lanjut langsung follow @casademiakitchen yaww\n\n#kulinerjogja #jogjafoodhunter #bukamejacemorojajar #bukamejacasademia #casademiakitchen', '2023-07-25T09:26:21.000Z', 'Positif'),
(906, 'dyodoran', 'salah satu kuliner pagi andalanku kalo lagi main di daerah Lempuyangan.\nsudah kedua kalinya aku kesini, jenangnya terverifikasi semlidut lezatos kotos kotosss\n\n#bubur #bubursumsum #jajananpasar #kulinerjogja #dyodoranjogja', '2023-07-22T09:30:00.000Z', 'Positif'),
(907, 'dyodoran', 'Trip kuliner di Wonosobo kemaren aku tutup dengan berburu Durian!!\nkalo kalian suka tipe durian yang kayak gimana lur??\n\n#durian #duren #culinary #dyodoran', '2023-07-19T09:36:34.000Z', 'Positif'),
(908, 'dyodoran', 'Seruu karena disini aku bisa ketemu sama kalian langsung \n\nOrder online/kirim ke penginapan\nchat WA Aja:  0818-0789-9499\n\n#oleholehjogja #oleholeh #tokosemlidut #wisatajogja #jogja', '2023-07-21T09:09:46.000Z', 'Positif'),
(909, 'dyodoran', 'KILAS BALIK AYAM PANGGANG DI KARANGANYAR!!!\n\nWarung ini aku datengin atas saran CCTV Warga Semlidut, katanya wajib banget dicoba dann akuu sangat bersyukurr dengerin usul kalian lurrrr\nAku intip dari proses masaknya, alat dan bahan masaknya.. super unik dan otentik!!\nJadi pengen balik kesini lagii wgwgwg \n\n#throwback #throwbackthursday #kulinerlegendaris\n#kulinerkaranganyar #ayampanggang', '2023-07-13T09:42:31.000Z', 'Positif'),
(910, 'dyodoran', 'SETELAH 5 TAHUN, MENU INI AKHIRNYA DIKELUARIN LAGI!! \n\nAda 1 menu favorit dari fruit bar langgananku, namanya Havana Ling. campuran kuah soda dan lemon yang nyegerinnn\n\nSelain comebacknya Havana Ling, ada banyak menu main course baru dan PAKET MERDEKA, modal 49ribuan bisa dapet 1 main course + 1 sup buah!\n\nDulu Havana Ling jadi favorit semua pelanggan, tapii karena antusias yang terlalu tinggi jadi gak kepegang dan setelah 5 tahun menunggu akhirnya dikeluarin lagi dongg berasa nostalgia deh kalo makan ini wgwgwg\n\nBuruan ke @bowllingid , tempatnya luas dan ada playground untuk anak-anak, bisa bikin acara juga lho di sinii\n\n#bowllingid #bowlling #bowllingconcat #jogjafoodies #kulinerjogja', '2023-08-23T09:30:00.000Z', 'Positif'),
(911, 'dyodoran', 'Jujurr setuju sama Mas Arief @kulineryogya , ini berasa kayak lagi war tiket konser konser internasionall wgwgwgwg\nIni kalo kamu datengnya kesorean, alamat gak kebagian sih soalnya yang antri was wes wos tenan lurrr \n\n#kulinerlegendaris #kulinerjogja #kulinerjogjakarta #streetfood #dyodoranjogja', '2023-07-14T09:31:08.000Z', 'Positif'),
(912, 'dyodoran', 'mie ayam TANPA MICIN porsi ugal ugalan yang lagi viral di Jogja lurrr!!\nada yang udah coba?? \n\n#mieayam #mieayamenak #mieayamjogja #kulinerjogja #dyodoranjogja', '2023-07-17T09:29:10.000Z', 'Positif'),
(913, 'dyodoran', 'SERING DIKIRA DISKOTIK, PADAHAL TEMPATNYA SUPER ESTETIK!! \n\nSiapa yang salah juga kayak aku?!\nJujur kalo diliat dari luar sih pasti mikirnya aneh-aneh, padahal tempatnya WOAH... instagramable pol dan fasilitasnya lengkap!!\nKita juga bisa ngadain acara karena ada hall multiple event yang muat sampai 200 orang\nKhusus di bulan JULI, ada banyak PROMO up to 20% dan extra PROMO MAHASISWA \n\nBuruan ajak temenmu kesini dan follow @downtowndiner.id untuk info promo selengkapnya yaa\n\n#kulinerjogja #jogjafood #jogjafoodhunter #nongkrongjogja #dyodoranjogja', '2023-07-15T04:30:00.000Z', 'Positif'),
(914, 'dyodoran', 'MAKAN PASTA MAHAL❌\nMAKAN PASTA DENGAN KEJU HARGA JUTAAN✅✅✅\n\nTrip Youtube ke Bandung, aku sempet makan pasta yang pakek keju Grana Padano\nIni tuh salah satu keju termahal otentik dari Italia!\nTersedia juga steak yang ukurannya ampun lur... GUEDE BANGETTT, sampe capek ngunyahnya\nWarga CCTV Semlidut Bandung udah ada yang coba?\n\n#pasta #kulinerbandung #bandungfoodies #bandungkuliner #dyodoran', '2023-08-16T09:22:16.000Z', 'Positif'),
(915, 'dyodoran', 'PERTAMA DI INDONESIA! COLLAB KITKAT X BAKPIA LOKAL JOGJA!!\n\nBakpia isi coklat memang banyak, tapi pernah gak kalian makan bakpia isi biskuit coklat Kitkat yang crunchy?\n\nBakpia isi Kitkat ini cuma bisa kalian temuin di store @bakpiajuwarasatoe !!\n\nNah saranku, sebelum di-hap, hangatkan dulu bakpianya pake microwave. Jadi coklat Kitkat dan tekstur bakpianya makin menyatu, perpaduan yang perfecto semliduto!!\n\nBakpia Juwara Satoe X Kitkat ini sehari cuma produksi 3000 pieces, jadi buruan cobain lurr karena waktunya terbatas!\n\nInfo pengiriman luar kota dan lainnya langsung cek ke @bakpiajuwarasatoe yaww\n\n#bakpiajuwarasatoe #kitkat #oleholehjogja #oleholeh #kulinerjogja', '2023-07-18T09:38:04.000Z', 'Positif'),
(916, 'dyodoran', 'Mana nehh yang kemaren minta di-spill lokasi Nasi Megono??\nIkii wis tak spill lokasinya. Emang agak mblusuk tapi.. \nSave & share yo lurrr biar gampang carinya!!\n\n#kulinerwonosobo #nasimegono #kulinerndeso #dyodoran', '2023-07-16T09:37:24.000Z', 'Positif');
INSERT INTO `dataset` (`id`, `owner`, `caption`, `timestamp`, `label`) VALUES
(917, 'dyodoran', 'PERTAMA KALI MAKAN BUBUR PAKE SEDOTAN!!\n\nNggak, ini bukan lomba sih.. aku lagi cobain cara beda buat nikmatin bubur semlidut yang wajib kalian coba kalo lagi di Jogja wgwgwg\n\nBukanya dari jam 6 pagi dan punya PAKET 10 RIBU, ini jadi salah satu pemadam perut keroncongan!\n\nApalagi Bubur Ketan Hitam Spesialnya BEUH.. masih jadi salah satu bubur ketan hitam terenak yang pernah aku makan!!\n\nKepingin to? Makanya ndang ke @buburhayam gerai Pusat atau Cabang Tasura ya lurr\n\n#kulinerjogja #jogjafood #jogjafoodhunter #buburhayam #dyodoranjogja', '2023-07-28T09:31:53.000Z', 'Positif'),
(918, 'dyodoran', 'JENANG CANDIL TERMAHAL YANG PERNAH AKU MAKAN!!\n\nDari 74 kota dan kabupaten yang pernah aku datengin, kuliner ini adalah salah satu yang ngena banget di lidah dan di dompet wgwgwgwg\nPer porsi isinya 5 candil, tapi kalo mau request lebih banyak atau lebih sedikit juga bisa!\nWarga CCTV Semlidut ada yang suka kesini juga gak nih??\n\n#kulinerwonosobo #jenang #jenangcandil #jajananpasar #dyodoran', '2023-07-12T09:42:24.000Z', 'Positif'),
(919, 'dyodoran', 'KULINER YANG DIBURU DI BANTUL!!\n\nkalo kalian belum pernah makan kepala kambing dan mau nyoba, ini adalah salah satu rekomendasiku!!\ntongseng kepala kambing di sini matangnya merata sampai ke dalam, bumbunya meresap dan yang paling penting gak prengus sama sekali\nsemlidut lezatos kotos kotoss\n\n#kepalakambing #tongsengkambing #kulinerjogja #kulinerunik #dyodoranjogja', '2023-07-11T09:31:40.000Z', 'Positif'),
(920, 'dyodoran', 'SETELAH 6 TAHUN, AKHIRNYA BUKA TEMPAT MAKAN JUGA!!\n\nKabar baik buat pecinta oseng mercon!\nAkhirnya oseng mercon ini buka warung juga lurrr\nLokasinya ada di antara warung tenda SS dan warung tenda Nasi Kulit Syuurga di GSP UGM\nAda yang udah nyobain belom nih?!\n\n#osengmercon #osengmercontugujogja #kulinerpedas #kulinerjogja #dyodoranjogja', '2023-07-10T09:29:02.000Z', 'Positif'),
(921, 'dyodoran', 'Hari ini konsepnya nostalgia ke salah satu tempat makan yang dulu lumayan sering aku datengin pas kuliah!\nHayoo, kalian udah ada yang kesini belum??\n\n#mieayam #mieayamjogja #siomay #kulinerjogja #dyodoranjogja', '2023-07-07T09:32:11.000Z', 'Positif'),
(922, 'dyodoran', 'warung in tuh salah satu kuliner yang wajib tak datengin tiap dateng ke Wonosobo!\nselain rasanya yang bikin kangen, vibes warungnya ini lho lur.. berasa lagi makan di rumah\n\n##kulinerwonosobo #wonosobo #dyodoran', '2023-07-08T09:30:00.000Z', 'Positif'),
(923, 'dyodoran', 'cakwe legend deket SKE Jogja!! aku udah lama gak beli, terus dapet info kalo sekarang bapaknya juga jual di pagi haril\nya langsung meluncur to~ \n\n#cakwe #gorengan #gorenganenak #kulinerjogja #dyodoranjogja', '2023-07-01T09:30:00.000Z', 'Positif'),
(924, 'dyodoran', 'NASI BEBEK JUMBO, BUKA DARI SIANG!!\n\nKabar bahagia buat pecinta bebek, sekarang akhirnya ada warung bebek goreng yang buka dari jam 12 siang!\n\nUkuran bebeknya BEUH… jumbo, ngenyangin pol! Kalo lagi diet, kalian bisa pesen bebek kecilnya\n\nNah minumannya ini lur yang bikin beda, karena ada Es Tape Gosrok Bahagia dan Es Badak Sarsaparilla! Pertama kalinya sihh aku nemu warung bebek dengan minuman kayak gini~\n\nAku makan di @nasibebek.bahagia , kalo dari utara ada di kiri jalan ya!\n\n#nasibebek #nasibebekjogja #kulinerjogja #jogjafoodhunter #dyodoranjogja', '2023-07-03T09:30:00.000Z', 'Positif'),
(925, 'dyodoran', 'kuliner lagi? Atau bahas toko oleh2? Atau bahas keseharian, atau ada masukkan apa dari kamu ? \n\n#threads @threadsapp', '2023-07-06T04:48:03.000Z', 'Netral'),
(926, 'dyodoran', 'kalo udah selesai explore gudeg dan bakmi godog, yang wajib kalian coba adalah sop buntut ini!\nbukanya emang cuma siang hari, tapi per harinya habis 1 kwintal iga & buntut sapi!\nkemaren aku ajak Mas @hobbymakan.id kesini~\nWarga CCTV Semlidut Jogja udah pernah coba?\n\n#sopbuntut #sopiga #sopigasapi #kulinerjogja #jogjafoodhunter', '2023-07-05T09:30:00.000Z', 'Positif'),
(927, 'dyodoran', 'salah satu streetfood kampus Sanata Dharma yang aku incer dari lama!!\nkalian ada yg suka jajan ini gak?\n\n#streetfood #streetfoodjogja #jasuke #gungsuju #dyodoranjogja', '2023-07-04T09:30:00.000Z', 'Positif'),
(928, 'dyodoran', 'JELAJAH KULINER FAVORIT PAK JOKOWI!! \n\nMain ke Solo kali ini cukup beda, karena aku mau jelajah kuliner legendaris dan kuliner favorit Pak Jokowi di acara @pucukharumid Festival Kuliner Legendaris!!\n\nTotal ada 80 kuliner yang bisa kalian coba!\nTiketnya masuknya GRATIS dan kalian bisa dapet iPhone 14 pro, 2 Instax dan jutaan hadiah lainnya dengan bikin konten \"A Day In Festival Kuliner Legendaris\"~\n\nAcaranya cuma sampe hari Minggu, 9 Juli 2023 di Benteng Vastenburgh Solo.\nNdang disamperin ya Besteaa\n\n#PucukGeneration #PucukinFestivalKulinerLegendaris #TehPucukHarumFestivalKulinerLegendaris #dyodoran', '2023-07-09T04:58:46.000Z', 'Positif'),
(929, 'dyodoran', 'PADAHAL BANYAK YANG CARI.. TAPI TETAP TIDAK BUKA CABANG!!\n\nKilas balik kuliner kali ini aku ajak kalian ke Karanganyar buat intip dapur kuliner terkenal: Ayam Tim Mbok Iyem!\nSpesialnya, disini pakek ayam kampung dengan proses masak selama 4 jam!\nTerus per paket ini sudah dapat beberapa jenis sambal juga lurr\nJadi kebayang kann enaknya kayak apa... \n\nAbsen dongg Warga CCTV Semlidut yang udah pernah nyobain inii \n\n#throwback #thrusdaythrowback #kulinerkaranganyar #kulinerlegendaris #dyodoran', '2023-07-06T09:28:35.000Z', 'Positif'),
(930, 'dyodoran', 'mampir ke mie nyemek fenomenal di selatan jogja bareng Mas @hobbymakan.id \nmeskipun nunggunya luamaaa, tapi sehari bisa jual sampe 200 mangkok Ihooo\nada yg udah coba?\n\n#mienyemek #mienyemekbusiti #kulinermalam #kulinerjogja #dyodoranjogja', '2023-07-02T09:30:00.000Z', 'Positif'),
(931, 'dyodoran', 'Siang ini lagi merenungi gak bangun di pagi hari padahal shalat Ied setahun sekali :(', '2023-06-29T05:39:48.000Z', 'Netral'),
(932, 'dyodoran', 'Belum grand opening , tapi kalau mau mampir udah buka ya @tokosemlidut oleh2 Jogjanya. Mau minta masukan apa aja yang masih perlu di perbaiki\n\nKalau kamu lagi sibuk wisata pesen Aja ke nomer WA ini ya 0818-0789-9499 biar kami anter \n\n#tokosemlidut #tokooleholehjogja #oleholehjogja #Jogja #threads', '2023-07-08T02:59:51.000Z', 'Positif'),
(933, 'dyodoran', 'FAMILY RESTO ANTI MAINSTREAM DENGAN VIEW GUNUNG MERAPI!!\n\nJujur aku baru pertama kali ke tempat ini dan langsung cocok sama vibesnya yang syahdu pol!!\n\nMenunya variatif dengan harga mulai dari 10 ribuan, super terjangkau apalagi buat mahasiswa yang butuh healingg wgwgwg\n\nSelain menu ala carte, kita juga bisa pesan menu by request, nasi box, hampers dan lainnya untuk area Jogja!\n\nAku makan di @yogyankopi . Buka dari jam 8 pagi dan tempatnya family friendly, jadi cocok buat sarapan di sini! Ndang ajak keluargamu lurrr\n\n#familyrestaurant #restokeluarga #kulinerjogja #jogjafood #jogjafoodhunter', '2023-06-30T12:00:00.000Z', 'Positif'),
(934, 'dyodoran', 'Liburan keluarga semakin berkesan dengan nikmatnya berbagai\nmenu otentik sunda di @lalawuhsunda spesialis menu Bakaran dan Pepes Ikan!\nNasi Liwet Spesial Kastrol, Cumi Asin Cabe Gendot, dan Gurameh Pesmol nya BEUH... juara lur!! Pantes jadi menu best seller~\nTempatnya instagramable, kids friendly dan cocok buat kumpul acara besar!\nBuruan agendakan acara keluarga kalian di @lalawuhsunda \n\nInfo & reservasi : 0811-2938-700', '2023-06-28T04:30:00.000Z', 'Positif'),
(935, 'dyodoran', 'Yang nyariin bakso di Jombor sekarang pindah kesini yaaaww\nAda yang langganan juga gak nih lurrr??\n\n#bakso #baksourat #baksosapi #kulinerjogja #dyodoranjogja', '2023-06-27T09:33:57.000Z', 'Positif'),
(936, 'dyodoran', 'Kilas balik kuliner yg sedang viral di Temanggung!!\nAku sama tim kesini udah sekitar 3 tahunan yang lalu\n\nWarung ini sudah berdiri sejak tahun 40an dan pas aku dateng, sudah diolah sama generasi ke-3!!\nSoal rasa gak perlu diraguin lagi lurrr\n\n#throwback #throwbackthursday #kulinertemanggung #kulinerlegendaris #dyodoran', '2023-06-29T09:30:00.000Z', 'Positif'),
(937, 'dyodoran', 'POV BAPACK2 BARU TAS PINK \nDengan seperangkat popok, tisu, botol dot dll \n\nCocok lah ya ? Wgwgwg\n\n#bendyoFamily #newbabyborn #newborn #stroller', '2023-07-01T04:39:47.000Z', 'Netral'),
(938, 'dyodoran', 'Warung ini cuma 10 menitan sebenernya kaloo dari rumahku, tapi baru pertama kalinya aku makan disini!\nGak nyangka ternyata warung in legend wgwgwg tau gitu dari dulu tak samperin\n\n#tongseng #satekambing #kulinerlegendaris #kulinerjogja #dyodoranjogja', '2023-06-24T09:30:35.000Z', 'Positif'),
(939, 'dyodoran', 'BIKIN TEH PAKE MESIN JAHIT??\n\nPertama kalinya aku nemu tempat minum teh yang seunik ini lurrr\nMulai dari bahannya, lokasinya, sampe cara bikinnya!\nAda yang pernah coba?\n\n#teh #tehtelur #kulinermalam #kulinerjogja #dyodoranjogja', '2023-06-25T09:30:00.000Z', 'Positif'),
(940, 'dyodoran', 'Kalo kesehatan mulai ngedrop, jajan jamu jadi pilihan pertama!\nIni tipikal warung jamu g rempahnya lumayan banyak dan hasilnya juga nendang!\nKalian biasanya pesen apa lur?\n\n#jamu #jamutradisional #kulinerjogja #jogjafood #dyodoranjogja', '2023-06-23T09:33:22.000Z', 'Positif'),
(941, 'dyodoran', 'Tebak kira2 besok siapa yang menjadi pemenangnya?\n- Baju Putih\n- Baju kotak2\n- Jaket jeans\n\nTayang hari Jum’at 23 Juni 2023 Jam 19.00 Di Channel YouTube Dyodoran\n\n#lombamakan #mukbang', '2023-06-22T12:53:58.000Z', 'Netral'),
(942, 'dyodoran', 'YANG LAGI VIRAL DI TIKTOK, ROTI SEHAT TANPA KIMIA AKHIRNYA BUKA TOKO!\n\nDi Tiktok lagi trend makan bluder pake susu!\nKalo aku rekomendasiin bluder langganan dari 2019 yang dibuat konsisten tanpa bahan pengawet, jadi lebih sehat!\n\nSelain bluder, di sini juga ada Bomboloni, Cake, Roti Tawar Bebas Gluten, Scone, dan puluhan jenis roti lainnya yang rasanya BEUH… wajib coba sendirii\n\nKalian bisa dapetin DISKON ALL ITEMS 10% dengan repost reels ini ke instastory, tulis kode promo \"DYO2001\" dan tag IG @hikarubakehouse.new dan @bludersusujogja , terus tunjukkin ke kasir dehh\n\nBerlaku cuma sampai tanggal 1 Agustus 2023 lhoo, ndang direpost terus jajan lur!!\n\n#bluder #hikarubakehouse #bludersusujogja #promohikaru #kulinerjogja #jogjafoodhunter', '2023-07-20T09:20:49.000Z', 'Positif'),
(943, 'dyodoran', 'Update @tokosemlidut \nUdah menjelang hari H sambil deg2an\nOiya buat UMKM yang udah ngirim sample ditunggu ya konfirmasinya \n\n#tokosemlidut #oleholehjogja', '2023-06-28T12:35:38.000Z', 'Positif'),
(944, 'dyodoran', 'SEHARI HABIS 1 KWINTAL AYAM?! \n\nini tuh salah satu ayam goreng lokal terkenal di Jogja yang sebelahan langsung sama ayam goreng label M itu lho lurr\nkemaren aku kesini sama Mas Evan @hobbymakan.id dan rasanya BEUH...\nkalian ada yang langganan kesini juga gak lur?\n\n#ayamgoreng #ayamgorengtepung #kulinerjogja #jogjafoodhunter #dyodoranjogja', '2023-06-26T09:30:00.000Z', 'Positif'),
(945, 'dyodoran', 'Spot soto yang satu ini langsung jadi langganan karena sotonya seger dan gorengannya itu lho...\nSelalu hangat!!\nHarganya juga murah, dan buat pecinta baling bisa request soto balungan!\nAda yg tau lokasi soto ini gak? \n\n#sotoayam #kulinerjogja #kulinerjogjamurah #jogjafood #dyodoranjogja', '2023-06-20T12:00:00.000Z', 'Positif'),
(946, 'dyodoran', 'CUMA DI SINI BISA KULINERAN BARENG PAK ERICK TOHIR!! \n\nKapan lagi ikut race terus menikmati berbagai kuliner khas Jogja di 1 tempat bareng Pak @erickthohir kalau bukan di acara Mandiri Jogja Marathon 2023?!\n\nYang bikin makin asyik, kalian bisa dapetin Cashback up to 50% dengan pembayaran via Kartu Kredit, Kartu Debit, dan QRIS Livin\' by Mandiri!\nPromo ini berlaku sampai akhir 30 Juni 2023 lho~\nList merchant bisa kalian cek di bmri.id/promojogja23 yaa\n\nFollow @mandirijogmar & @bankmandiri untuk info selengkapnya dan jumpa di Mandiri Jogja Marathon 2024 lur! \n\n#MajukanEnergiIndonesia #MJM2023', '2023-06-21T09:30:00.000Z', 'Positif'),
(947, 'dyodoran', 'BURGER SOMBONG YANG CUMA BUKA 2X SEMINGGU!!\n\nBun burgernya lembut dan pas digigit bareng saus signaturenya BEUH... semlidutt\nTempatnya juga asik buat ngobrol bareng temen temen!\nNdang dicoba lurr~\n\n#burger #kulinerjogja #dyodoran', '2023-06-19T09:30:00.000Z', 'Positif'),
(948, 'dyodoran', 'DI PROTES‼️\n“Mas mbok borong warung kecil aja” Okay siap langsung di kabulkan\n\nTayang malem ini jam 7 di YouTube Dyodoran \n\nDi tonton ya sambil ninggalin jejak, kalau rame aku lanjutin \n\n#warungklontong', '2023-06-16T05:35:00.000Z', 'Positif'),
(949, 'dyodoran', 'Menurutku ini cocok buat kalian yang suka ngegrill tanpa batasan waktu!\nPudingnya rekomendid bener lurr, semliduttt \n\n#japanesegrill #kulinerjogja #jogjafoodies #jogjafoodhunter #dyodoranjogja', '2023-06-17T09:28:58.000Z', 'Positif'),
(950, 'dyodoran', 'Sebelumnya aku dah beberapa kali makan disini dan cocok!\nYang aku suka disini tuh ada tambahan topping paru dan isian baksonya BEUH!!\nAda yang udah pernah coba??\n\n#kulinerjogja #bakso #baksosapi #kulinerlegendaris #dyodoranjogja', '2023-06-16T12:00:00.000Z', 'Positif'),
(951, 'dyodoran', 'Kalo kalian ketemu Mas Dyo, kira kira bakal borong apa lur?\n\n#borong #belanjamurah #belanjagratis', '2023-06-14T09:30:00.000Z', 'Netral'),
(952, 'dyodoran', 'Biar ngajinya pada tambah semangat ya adek adek TPA\nPOV CaLeg', '2023-06-15T05:00:00.000Z', 'Positif'),
(953, 'dyodoran', 'KULINER SETAN, IBUNYA TAKUT LARIS?!\n\nKilas balik hari ini aku mau ajak kalian main ke daerah Tegal!\nKuliner ini jadi salah satu makanan yang direquest sama Warga CCTV Semlidut buat diliput karenaaa namanya yang unik dan pedesnya menggelegar lurrr\nSebenernya ini cuma tempe orek yang dimasak sama kuah pedes, tapii yang antriii BEUH... luar biasa!!\nAda yang berani makan ini?\n\n#throwback #throwbackthursday #kulinertegal #kulinerlegendaris #dyodoran', '2023-06-15T09:30:00.000Z', 'Positif'),
(954, 'dyodoran', 'Kilas balik momen BORONG KEPALA KAMBING!!\n\nWarga CCTV Tegal mana nih suaranya??\nTegal terkenal akan olahan kepala kambingnya, jadi ya langsung tak mampir~\nWarungnya sudah jualan 3 generasi, jadi rasanya BEUH... terverifikasi semlidut!\n\n#throwback #throwbackthursday #kepalakambing #kulienelegendaris #kulinertegal', '2023-06-22T09:30:04.000Z', 'Positif'),
(955, 'dyodoran', 'SAME KEHABISAN NAPAS!!\n\nGa sengaja, ternyata stranger yg aku tantang adalah seorang ibu yg punya anak umur 3 tahun!\nMenurut kalian udah cukup banyak belum nih ibu mborongnya?\n\n#borong #belanjamurah #belanjagratis', '2023-06-18T09:30:00.000Z', 'Positif'),
(956, 'dyodoran', 'UPDATE TOKO SEMLIDUT\nhari ini akan aku chat 1-1 ya untuk jadwal kurasinya \n\n#TokoSemlidut #OlehOlehJogja', '2023-06-14T04:32:21.000Z', 'Positif'),
(957, 'dyodoran', 'Duluu kuliner ini viral karena jualan ketoprak pake mobil kodok dann jualannya pas depan kuburan kristen terkenal di Jogja!\nJebul wis pindah, makanya aku update disini wgwgwg\nIni tipikal ketoprak yang puedesnya nampol, jadi tak saranin cabenya dikit aja kalo kalian mau tidur dengan tenang yawww\n\n#ketoprak #kulinermalam #kulinerjogja #kulinermalamjogja #dyodoranjogja', '2023-06-13T09:30:00.000Z', 'Positif'),
(958, 'dyodoran', 'AAHHHH akhirnya ada pendatang gelato baru lagi lurrr di Jogjaa!!\nDi lokasinya pas depan Tamansari, jadi pas banget abis panas panasan langsung ngadem disini!!\nSemlidut lezatos kotos kotosss\n\n#gelato #gelatojogja #kulinerjogja #jogjafood #jogjafoodhunter', '2023-06-05T09:30:00.000Z', 'Positif'),
(959, 'dyodoran', 'MENGGILA DI BANDUNG!!!\n\nMain ke Braga, Bandung, rasanya agak kureng kalo gak mampir ke toko satu ini\nBuat para pecinta es krim, menurutku kalian pasti bakal jatuh cinta sama es krim\ncokelatnya!\nJoss tenann semlidut lezatos kotos kotosss\n\n#kulinerbandung #tahilalats #bandungkuliner #bandungfoodies', '2023-06-11T09:30:00.000Z', 'Positif'),
(960, 'dyodoran', 'Rolasaaaannnn sekkkk Lurrrrr', '2023-06-08T04:44:23.000Z', 'Positif'),
(961, 'dyodoran', 'Seperti yang kebanyakan orang tau, Lumpia tuh ikon kulinernya Semarang\nTapii di Jogja juga ada Iho!\nIni pertama kalinya aku makan Lumpia ala Jogja\nSaosnya beda banget sama Lumpia Semarang, tetep joss semlidut lezatos kotos kotos... \n\n#lumpia #lumpiagoreng #kulinerlegendaris #kulinerjogja #dyodoranjogja', '2023-06-06T09:30:00.000Z', 'Positif'),
(962, 'dyodoran', 'nambah lagiii kuliner fancy di Jogja!\nmenurutku kalo untuk self reward sih ini sudah sangat cukup yaww\nasal jangan keseringan lurrr ben gak cepet kempes dompetmu\n\nbtw Warga CCTV Semlidut udah ada yang kesini belum?\n\n#kulinerjogja #jogjafood #jogjafoodhunter #cafejogja #dyodoranjogja', '2023-06-04T09:30:00.000Z', 'Positif'),
(963, 'dyodoran', 'PERTAMA KALI IKUT KELAS BIKIN BAKPIA!!\n\nMeskipun udah lama tinggal di Jogja dan sering nyemil Bakpia, ini pertama kalinya aku tau ada kelas bikin Bakpia!\n\nSelesai bikin Bakpia lanjut kita belanja~ Tempatnya luas pol! Fasilitasnya lengkap, ada masjid dan parkirannya juga luas. Kapasitas area restonya bisa untuk 1000pax! \n\nMenurutku tempatnya oke sih buat tujuan wisata terakhir karena ini adalah tempat oleh-oleh terlengkap dan terbesar di Jogja, apalagi bakal ada mini zoo disini \n\nInfo kelas Bakpia lebih lanjut langsung follow @ibarbopark !\n\n#oleholeh #oleholehjogja #jogjafoodhunter #jogjafooddestinations #ibarbopark', '2023-06-12T09:33:36.000Z', 'Positif'),
(964, 'dyodoran', 'salah satu jajanan favorit soalnyaa lumayan buat ngganjel perut pas lagi moving dari warung ke warung wgwgwgwg\nkalo kalian lebih suka cimol, kentang, atau ubi lur?\n\n#streetfood #kentanggoreng #dyodoran', '2023-06-10T09:30:00.000Z', 'Positif'),
(965, 'dyodoran', 'Semangat hari Senin Om Tante semuaaa ‍ \n\n#bendyofamily', '2023-06-12T03:04:09.000Z', 'Positif'),
(966, 'dyodoran', 'Agak kaget sih pas tau nama warung ini persis kayak warung bebek terkenal di Surabaya.\nArek Suroboyo, pie kii rasane podo ta gakk??\n\n#bebeksurabaya #nasibebek #kulinerjogja #kulinerjogjamurah #dyodoranjogja', '2023-06-03T09:30:00.000Z', 'Positif'),
(967, 'dyodoran', 'Menurutku, soto tuh satu kuliner yang cocok di segala suasana\nDimakan pagi sing malem cocok.. pas lagi panas atau hujan makin nikmat!\nNah kali ini aku mbahas soto legendaris yang terkenal di Jogja dan ada beberapa cabangnya!\nTapi kira kira mana yang asli ya lur?\n\n#soto #sotosapi #kulinerlegendaris #kulinerjogja #dyodoranjogja', '2023-06-02T09:30:00.000Z', 'Positif'),
(968, 'dyodoran', 'Warga CCTV Semlidut area Mbantul pasti gak asing sama kuliner ini!\nBuka dari tahun 50-an, dan antriannya ngeri lurrr..\nKalo ada cabangnya di tengah kota, aku pasti bakal sering pesen!!\n\n#tongseng #tongsengayam #kulinerlegendaris #kulinerjogja #dyodoranjogja', '2023-05-30T09:30:00.000Z', 'Positif'),
(969, 'dyodoran', 'Kilas balik kali ini aku mau bawa kalian ke Bandung!\n\nKuliner legendaris yang dijual dari tahun 1980.\nAwalnya jualan bakso, terus terpikirlah buat bikin menu iniii\nUniknya disini ada 2 versi lur, goreng & kuah!\nAda yang tau gak nih aku makan dimana? \n\n#throwback #throwbackthursday #kulinerbandung #kulinerbandungjuara #batagor', '2023-06-01T12:00:00.000Z', 'Positif'),
(970, 'dyodoran', 'Hehehehe…\nAlhamdulillah \n\n#newborn #newbornbaby #BenDyoFamily #masKenzie', '2023-05-31T04:30:07.000Z', 'Positif'),
(971, 'psnovi', 'Teh tubruk kah ini namanya?!\nBaru tau sih ini namanya produk Angkringan.. nah kemarin Beli Di toko dari jogja, dikirim dari sekitaran jogja ini.. teh nya Di mix satu, wanginya Jadi nge blend, enak ada pait dan wangi melati  Besok kita coba Makanan daerah mana lagi nih?!\n\n#PSNovi', '2023-06-02T05:05:08.000Z', 'Positif'),
(972, 'dyodoran', 'Iga panggang yang lagi rameee di Jakartaa!!\nIni gokil sih, soalnya sehari tuh bisa sampe buka 3 sesi dan 1,5 jam aja langsung habis!\nWarga CCTV Semlidut udah pada kesini belum??\n\n#igapanggang #kulinerjakarta #kulinerjakartaselatan #igabakar #dyodoranjakarta', '2023-05-27T09:30:00.000Z', 'Positif'),
(973, 'dyodoran', 'WARTEG ARTSY BARU DI JALAN KABUPATEN!!\n\nUntuk masuknya memang agak mblusuk siih, tapi makanannya lurr… semlidut!!\n\nMenurutku, kalian harus coba ikan asap, cumi hitam plus sambel ndeso nya. Untuk dessert-nya jangan kelewat nyobain flan dan es kuwut.\n\nKalo masih ada, garang asemnya juga ndang disikat!!\n\nAku makan di @vindotyskitchen . Tempatnya homey, serasa makan di rumah!\n\n‌\n\n#nostalgiarasa #wartegjogja #hiddengemjogja #jogjafoodhunter #dyodoranjogja', '2023-05-26T09:30:00.000Z', 'Positif'),
(974, 'dyodoran', 'LARIS MANIS TANJUNG KIMPUL!!\n\nKilas balik hari ini mau ngebahas salah satu kuliner legendaris Ayam Adun Pelabuhan Bu Mani di Gresik!\n\nBuka dari jam 5 pagi, jam 8 udah abis lurr yaampun untung aku masih kedapetan!\n\nKomen dong kalo kalian pernah kesini!\n\n#throwback #throwbackthursday #kulinerlegendaris #kulinergresik #dyodoran', '2023-05-25T09:30:00.000Z', 'Positif'),
(975, 'dyodoran', 'Kalo kalian mau nyobain kuliner yg agak beda, coba deh pesen menu spesial di tempat ini!\nSoalnya aku bahkan gak nemuin menu ini di kota asalnya lurrr wgwgwg\n\n#bakmi #bakmijawa #kulinerjogja #jogjafoodhunter #dyodoranjogja', '2023-06-09T09:30:00.000Z', 'Positif'),
(976, 'dyodoran', 'Aku punya rekomendasi buat kalian yang mau kulineran di Solo dengan waktu terbatas!!\nNext coba kuliner apa lagi ya?\n\n#kulinersolo #kulinersoloenak #kulinersolomurah', '2023-05-29T09:30:08.000Z', 'Positif'),
(977, 'dyodoran', 'Cuma jualan nasi + telur bisa dapet omset 7juta lurrr sebulannn wgwgwg\nKalian wis do nyoba belum nihh??\n\n#nasitelur #kulinerviral #kulinerjogja #kulinerjogjamurah #dyodoranjogja', '2023-05-31T09:30:00.000Z', 'Positif'),
(978, 'dyodoran', 'Bismillah minta doanya ya semuanya \nKalau yg mau nonton fullnya bisa di Channel yuhub Dyodoran \n\n#kulinerjogja #Rotibakar #jogja', '2023-05-25T13:06:48.000Z', 'Positif'),
(979, 'dyodoran', 'Auto belanja banyak sih karna perlengkapan bayi di @babyzania.jogja lucu-lucu bangetttt! \n\nMulai dari perlengkapan bayi, kepentingan toiletris sampai spa untuk bayi dan anak juga ada lho! Bisa kalian cek juga di marketplace Baby Zania Jogja\n\nNah ada info promo nih:\n- Pembelian 500k free sepatu (selama persediaan masih ada)\n- KHUSUS MEMBER pembelian 100k mendapatkan poin, yang bisa ditukarkan dengan berbagaI jenis hadiah\n\nDi sini FREE pembuatan member setiap hari SELASA dengan min. belanja 200k atau 500k dengan biaya admin 10k.\n\nKeuntungan memiliki member bisa mendapatkan disc 5% - 10% per item, dan dapet poin yg bisa ditukarkan sama berbagai macam kebutuhan baby. Buruan bikin member bisa makin puas belanjanya! \n\nWA : 0877-7086-3636\nTelf : ( 0274 ) 487836', '2023-05-22T09:30:00.000Z', 'Positif'),
(980, 'dyodoran', 'RAMEN HIDDEN GEM YANG DISKON SETIAP HARI!! \n\nSebelumnya aku pernah makan disini dan terverifikasi semlidut\nEh terus ada menu baru, ya langsung too tak samperinn\n\nAda 3 menu baru yang wajib kalian coba: Izumi Spesial Tamtam, Samurai Komakura, dan Corn Ribs sebagai side dishnya\nKuah ramennya dimasak sampe 8 jam lurr, menghasilkan rasa yang… HADEEHH, kalian cobain sendiri deh wgwgwg\n\nLokasinya ada di Jl. Sidokabul No.8, Sorosutan Umbulharjo\nBuka dari jam 11.00-21.00, diskon 15% setiap harinya!\nInfo lebih lanjut langsung cek @roka.id \n\n‌#ramen #ramenhalal #ramenjogja #kulinerjogja #dyodoranjogja', '2023-05-24T09:30:00.000Z', 'Positif'),
(981, 'dyodoran', '5000 UDAH DAPET PAKET KOMPLIT?!\n\nmahasiswa wajib merapat, aku nemu warung ramesan murah ramah di kantong!\nwarung ini dah buka dari tahun 1970an dengan beberap menu berbeda tiap harinya\nkalian ada yang suka kesini gak lurrr?\n\n#kulinerjogja #kulinerjogjamurah #kulinermahasiswa #jogjafoodhunter #dyodoranjogja', '2023-05-21T09:30:00.000Z', 'Positif'),
(982, 'dyodoran', 'HIDDEN GEM FAMILY RESTO DI RINGROAD TIMUR!!\n\nMenurutku ini tempat yang pas buat recharge energi karena lokasinya ga jauh, cuma 5 menit dari Jogja Expo Center!\n\nMenunya beragam dan menurutku yang wajib kalian coba tuh: Empal Gentong, Bakmie Jawa Goreng sama Ayam Kampung Bakarnya! Terverifikasi semlidut lurr\n\nGurame Bakarnya juga rekomendid buat disantap bareng keluarga\n\nTempatnya juga sejuk, parkirnya luas, fasilitasnya lengkap dan ada wahana bermain anak!\n\nAku makan di @pawonjati_jogja by Nusantara Catering\n\n‌#familyresto #familyrestojogja #pawonjati #kulinerjogja #jogjafoodies', '2023-05-20T09:30:00.000Z', 'Positif'),
(983, 'dyodoran', 'Maaf ya aku batasi karena raknya juga terbatas, Aku tunggu pendaftarannya sampai tgl 30 Mei 2023 \n\nLinknya di copy ke browser:\nhttps://bit.ly/DaftarUMKMTokoSemlidut\n\n#tokosemlidut #oleholehjogja', '2023-05-21T03:26:37.000Z', 'Positif'),
(984, 'dyodoran', 'MUKBANG KEPALA KAMBING UTUH DI JOGJA SELATAN\n\nAda warung sate kambing baru di Selatan yang punya nasi FREE REFILL dan KERUPUK GRATIS!!\n\nFYI, biasanya sate klatak itu disajikan bareng kuah gulai yang light, makanya pas makan sate klatak kuah tongseng di @satekambingmbahdjoyo tuh sensasi beda! Semlidut lezatos kotos kotosss\n\nTempatnya nyaman, parkiran luas dan bisa menampung sampai 40 orang! Cocok banget ki lurr buat kumpul bareng temen-temen atau keluarga~\n\nInfo pemesanan bisa langsung chat via Whatsapp +62 821-3480-4034\n\n#kepalakambing #satekambing #sateklatak #satekambingmbahdjoyo #kulinerjogja', '2023-05-17T09:27:13.000Z', 'Positif'),
(985, 'dyodoran', 'Jajan di pasar tuh jadi salah satu kegiatan healing\ntipis tipis, soalnya seru aja gituu ngeliat\ninteraksinyaa\nAda yang saman gak? \n\n#kulinerjogja #kulinerjogjamurah #dyodoranjogja #jogjafoodhunter #jogjaistimewa', '2023-05-19T09:30:00.000Z', 'Positif'),
(986, 'dyodoran', 'Bismillah biar kayak yg lain punya usaha \nTebak aku mau buka apa?\n3 orang yg bener aku kirim masing2 300.000', '2023-05-16T09:00:00.000Z', 'Positif'),
(987, 'dyodoran', 'INTIP DAPUR TRADISIONAL GUDEG OTENTIK!\n\nIni salah satu top brand gudeg dengan rasa manis khas jogjaan\n\nUniknya, Gudeg Yu Djum 167 mengeluarkan Gudeg Frozen tanpa pengawet yang tahan sampe 3 bulan!\n\nSecara rasa ga akan berubah dan tetap aman buat dikirim ke berbagai kota\n\nSelain itu ada gudeg kaleng ready to eat, bisa langsung dimakan atau mau dipanasin bebass\n\nKalo aku sih langsung makan aja ya, wis keburu ngiler lurrr wgwgwg\n\nCatet ya, Gudeg Frozen Yu Djum 167, bukan yang lain!\n\n#gudegyudjum167 #gudegyudjum #gudegjogja #gudegfrozen #gudegkaleng', '2023-05-15T04:26:34.000Z', 'Positif'),
(988, 'dyodoran', 'PERTAMA KALI DATENG KE PESTA MAKAN NASI GORENG TERBESAR!!\n‌\nGak cuma nasi goreng yaa, berbagai menu khas nusantara ada disini!\nMakin seru karena ada Live Cooking dari @willgoz \nPesta Kuliner Sedaap bakal ada lagi di Bandung, 27 Mei 2023\nTiketnya bisa langsung beli on the spot ya lurr\nInfo lebih lanjut langsung follow @kecapsedaapid\n\n#PestaKulinerSedaap #NasiGorengPilihanSedaap #TastExploration', '2023-05-15T09:30:00.000Z', 'Negatif'),
(989, 'dyodoran', 'Kilas balik kota ke 59, Gresik!!\n\nAku inget, dari luar warungnya aja sudah tercium wangi masakan yang menggoda iman!\n\nPas makanannya dateng, kaget lurr ndelok porsine sak gedabyah!\n\nAda yang tau gak nihh aku makan di warung manaa?\n\n#throwback #throwbackthursday #gresik #gresikhits #gresikkuliner #kulinergresik', '2023-05-18T09:37:12.000Z', 'Negatif'),
(990, 'dyodoran', 'Ini tuh satu satunya tempat yang jual Bakso CepMek alias Cepet Mekar HAHAHAHA\nAgak kesel denger namanya, tapi rasanya BEUH... mantap!!\nTapi tetep, yang paling favorit ya bakso uratnya lurrr\nWarga Bandung udah pada nyobain belum nih?\n\n#baksobandung #kulinerbandung #kulinerbandungjuara #baksotjaphaji #bandungfoodies', '2023-05-23T09:30:00.000Z', 'Negatif'),
(991, 'dyodoran', 'Ini adalah salah satu kuliner yang wajib disamperin kalo lagi main ke Bandung!\n\nDengan title \"Sensasi Cita Rasa Nasi Goreng Sang Legend\", rasanya BEUH.. semlidut!\nMana porsinya jumbo lagi, jadi makin puass wgwgwg \n\nKalian ada yang langganan kesini juga ga lur?\n\n#throwback #throwbackthursday #kulinerbandung #kulinerlegendaris', '2023-05-11T09:27:10.000Z', 'Negatif'),
(992, 'dyodoran', 'Bismillah \nUdah mulai seminggu sekali kontrolnya ‍\n\n#bapakbapaksiaga #babynewborn #ibuhamil', '2023-05-13T04:05:28.000Z', 'Negatif'),
(993, 'dyodoran', 'BIKIN IDE MINUMAN BISA DAPET KESEMPATAN MENANGIN VESPA ATAU IPHONE 14 PRO MAX??\n\nKalian ga salah baca lurrr\n\n#Coffeemezation dari @starbucks.indonesia balik lagi nih!\n\nDengan daftarin ide minuman andalan kalian di coffeemezation.com, kalian berkesempatan buat menangin Vespa Piaggio, iPhone 14 Pro Max dan jutaan hadiah lainnya!\n\nLangsung submit ide minuman kalian maksimal BESOK! tanggal 14 Mei 2023 buat diundi jadi finalist untuk menangin hadiah total ratusan juta rupiahnya!\n\nInfo lengkap langsung cek postingan @starbucksindonesia ya\n\n#Coffeemezation #StarbucksIndonesia #iceAmericano #coffeecompetition', '2023-05-12T12:00:00.000Z', 'Negatif'),
(994, 'dyodoran', 'street food yang lagi viral di Jogja!!\nhayooo, yang kemaren pada liburan ke Jogja wis mampir rene durung??\n\n#kulinerjogja #jogjafood #jogjafoodhunter #jogjafoodies #gulesatelitjogja', '2023-05-07T09:30:00.000Z', 'Negatif'),
(995, 'dyodoran', 'Yang lagi ramere di Pasmod Bintaro!!\nNasinya spesialnya karena dibungkus daun pisang, jadi lebih wangii\nSemlidut lezatos kotos kotoss\n\nKalian ada yg suka kesini juga gak?\n\n#kulinerbintaro #kulinertangsel #bintarofoodies #ayamkampung #dyodoranbintaro', '2023-05-13T09:30:00.000Z', 'Negatif'),
(996, 'dyodoran', 'SPESIALIS GULE JEROAN SEJAK 1945!\nJadi Pasar Godean tu lagi direnovasi dan makan waktu sekitar 1,5 tahun\nNah untungnyaa, Warung Sate Pak Klimkn gak pindah karena sudah punya bangunan sendiri!\nKalian wis do nyobo rung lurrr??\n\n#satekambing #tongseng #kulinerjogja #kulinerlegendaris #dyodoranjogja', '2023-05-09T09:30:00.000Z', 'Negatif'),
(997, 'dyodoran', 'sebenernya dah lewat tempat in beberapa kali atpi belum sempet mampirr\nsampe akhirnyaaa kena racun dari temenkuu wgwgwg\nmind blowing ya lur, singkong goreng dikasi truffle oil \n\n#kulinerjogja #restojogja #jogjafoodhunter #jogjafood #dyodoranjogja', '2023-06-07T09:30:00.000Z', 'Negatif'),
(998, 'dyodoran', 'Jogja punya salah satu warung sop buntut yang semlidutt dan ini dia tempatnya!\nMulai usaha tahun 1985, awalnya sempet coba coba jualan makanan yg lain sampe akhirnya memutuskan jual sop buntut dan hasilnya WOW bisa sampe berangkat haji lurr\nKalian ada yg langganan disini juga gak?\n\n#sopbuntut #sopiga #kulinerlegendaris #kulinerjogja #jogjafoodhunter', '2023-05-08T09:30:00.000Z', 'Negatif'),
(999, 'dyodoran', 'SAMPE SUSAH MAKANNYA!! \n\nAku direkomendasiin kuliner ini sama salah\nWarga CCTV Semlidut \nLangsunglah meluncur ke selatan Jogja dan ternyataaa BEUH.... porsine ngeri lurrr\nAsik banget nii kalo makan bareng temen temenn\n\n#mieayam #mieayambalungan #kulinerjogjamurah #kulinerjogja #dyodoranjogja', '2023-05-10T09:30:00.000Z', 'Negatif'),
(1000, 'dyodoran', 'Kilas balik ES LONTRONG!\n\nAku main ke kedai es ini 2 tahun yang lalu pas lagi syuting kuliner legendaris di Tegal.\nKedai es ini sudah ada sejak tahun 80an, dengan menu es berisi kacang hijau, agar-agar, santan, gula dan es gosrok yang segununggg \nHarga per porsinya waktu itu sih cuma 5000 yaa, kalo ada info update harga boleh dong lurrr komen di bawaah \n\n#throwback #throwbackthursday #kulinertegal #eslontrong #kulinerlegendaris #dyodoran', '2023-06-08T09:30:00.000Z', 'Negatif');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `dataset`
--
ALTER TABLE `dataset`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `dataset`
--
ALTER TABLE `dataset`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=1001;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
